// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_deletion_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccountDeletionRequest = `-- name: CreateAccountDeletionRequest :one
insert into account_deletion_requests (user_id)
values ($1)
on conflict (user_id) do nothing
returning id, user_id, requested_at, status, completed_at
`

// `on conflict do nothing` — idempoten, ahli boleh tekan "padam akaun"
// berkali-kali tanpa ralat (padanan pola AddBlockedEmailDomain). Baris
// SEDIA ADA (bukan yang baru dicuba) yang perlu dipulangkan pada
// konflik — lihat GetAccountDeletionRequestByUserID di handler.
func (q *Queries) CreateAccountDeletionRequest(ctx context.Context, userID uuid.UUID) (AccountDeletionRequest, error) {
	row := q.db.QueryRow(ctx, createAccountDeletionRequest, userID)
	var i AccountDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedAt,
		&i.Status,
		&i.CompletedAt,
	)
	return i, err
}

const getAccountDeletionRequestByUserID = `-- name: GetAccountDeletionRequestByUserID :one
select id, user_id, requested_at, status, completed_at from account_deletion_requests where user_id = $1
`

// Guna oleh CreateAccountDeletionRequest bila insert kena `on conflict do
// nothing` (tiada baris dipulangkan), dan utk pelaporan/staff semak status
// kemudian.
func (q *Queries) GetAccountDeletionRequestByUserID(ctx context.Context, userID uuid.UUID) (AccountDeletionRequest, error) {
	row := q.db.QueryRow(ctx, getAccountDeletionRequestByUserID, userID)
	var i AccountDeletionRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedAt,
		&i.Status,
		&i.CompletedAt,
	)
	return i, err
}
