// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActivitySessions = `-- name: CountActivitySessions :one
select count(*) from activity_sessions where activity_id = $1
`

func (q *Queries) CountActivitySessions(ctx context.Context, activityID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivitySessions, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsWithAttendance = `-- name: CountSessionsWithAttendance :one
select count(*) from activity_sessions s
where s.activity_id = $1
  and exists (select 1 from activity_attendances a where a.session_id = s.id)
`

// Menghalang penggantian set sesi yang akan membuang kehadiran yang sudah
// direkod.
func (q *Queries) CountSessionsWithAttendance(ctx context.Context, activityID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsWithAttendance, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
insert into activities (
  category_id, title, description, location_name, location_address,
  starts_at, ends_at, registration_opens_at, registration_closes_at,
  capacity, fee_cents, attendance_threshold_pct, created_by
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
returning id, category_id, title, description, location_name, location_address, starts_at, ends_at, registration_opens_at, registration_closes_at, capacity, fee_cents, currency, attendance_threshold_pct, status, cancelled_reason, certificates_issued_at, created_by, created_at, updated_at, deleted_at
`

type CreateActivityParams struct {
	CategoryID             uuid.UUID          `json:"category_id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	LocationName           string             `json:"location_name"`
	LocationAddress        string             `json:"location_address"`
	StartsAt               pgtype.Timestamptz `json:"starts_at"`
	EndsAt                 pgtype.Timestamptz `json:"ends_at"`
	RegistrationOpensAt    pgtype.Timestamptz `json:"registration_opens_at"`
	RegistrationClosesAt   pgtype.Timestamptz `json:"registration_closes_at"`
	Capacity               pgtype.Int4        `json:"capacity"`
	FeeCents               int32              `json:"fee_cents"`
	AttendanceThresholdPct int16              `json:"attendance_threshold_pct"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.LocationName,
		arg.LocationAddress,
		arg.StartsAt,
		arg.EndsAt,
		arg.RegistrationOpensAt,
		arg.RegistrationClosesAt,
		arg.Capacity,
		arg.FeeCents,
		arg.AttendanceThresholdPct,
		arg.CreatedBy,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.Capacity,
		&i.FeeCents,
		&i.Currency,
		&i.AttendanceThresholdPct,
		&i.Status,
		&i.CancelledReason,
		&i.CertificatesIssuedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createActivitySession = `-- name: CreateActivitySession :one
insert into activity_sessions (activity_id, seq, title, starts_at, ends_at)
values ($1, $2, $3, $4, $5)
returning id, activity_id, seq, title, starts_at, ends_at
`

type CreateActivitySessionParams struct {
	ActivityID uuid.UUID          `json:"activity_id"`
	Seq        int32              `json:"seq"`
	Title      string             `json:"title"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	EndsAt     pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateActivitySession(ctx context.Context, arg CreateActivitySessionParams) (ActivitySession, error) {
	row := q.db.QueryRow(ctx, createActivitySession,
		arg.ActivityID,
		arg.Seq,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i ActivitySession
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Seq,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const deleteActivitySessions = `-- name: DeleteActivitySessions :exec
delete from activity_sessions where activity_id = $1
`

func (q *Queries) DeleteActivitySessions(ctx context.Context, activityID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteActivitySessions, activityID)
	return err
}

const getActivityByID = `-- name: GetActivityByID :one
select a.id, a.category_id, a.title, a.description, a.location_name, a.location_address, a.starts_at, a.ends_at, a.registration_opens_at, a.registration_closes_at, a.capacity, a.fee_cents, a.currency, a.attendance_threshold_pct, a.status, a.cancelled_reason, a.certificates_issued_at, a.created_by, a.created_at, a.updated_at, a.deleted_at, c.key as category_key, c.name as category_name
from activities a
join activity_categories c on c.id = a.category_id
where a.id = $1 and a.deleted_at is null
`

type GetActivityByIDRow struct {
	ID                     uuid.UUID          `json:"id"`
	CategoryID             uuid.UUID          `json:"category_id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	LocationName           string             `json:"location_name"`
	LocationAddress        string             `json:"location_address"`
	StartsAt               pgtype.Timestamptz `json:"starts_at"`
	EndsAt                 pgtype.Timestamptz `json:"ends_at"`
	RegistrationOpensAt    pgtype.Timestamptz `json:"registration_opens_at"`
	RegistrationClosesAt   pgtype.Timestamptz `json:"registration_closes_at"`
	Capacity               pgtype.Int4        `json:"capacity"`
	FeeCents               int32              `json:"fee_cents"`
	Currency               string             `json:"currency"`
	AttendanceThresholdPct int16              `json:"attendance_threshold_pct"`
	Status                 string             `json:"status"`
	CancelledReason        pgtype.Text        `json:"cancelled_reason"`
	CertificatesIssuedAt   pgtype.Timestamptz `json:"certificates_issued_at"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CategoryKey            string             `json:"category_key"`
	CategoryName           string             `json:"category_name"`
}

func (q *Queries) GetActivityByID(ctx context.Context, id uuid.UUID) (GetActivityByIDRow, error) {
	row := q.db.QueryRow(ctx, getActivityByID, id)
	var i GetActivityByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.Capacity,
		&i.FeeCents,
		&i.Currency,
		&i.AttendanceThresholdPct,
		&i.Status,
		&i.CancelledReason,
		&i.CertificatesIssuedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryKey,
		&i.CategoryName,
	)
	return i, err
}

const getActivitySessionByID = `-- name: GetActivitySessionByID :one
select id, activity_id, seq, title, starts_at, ends_at from activity_sessions where id = $1
`

func (q *Queries) GetActivitySessionByID(ctx context.Context, id uuid.UUID) (ActivitySession, error) {
	row := q.db.QueryRow(ctx, getActivitySessionByID, id)
	var i ActivitySession
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Seq,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
select a.id, a.category_id, a.title, a.description, a.location_name, a.location_address, a.starts_at, a.ends_at, a.registration_opens_at, a.registration_closes_at, a.capacity, a.fee_cents, a.currency, a.attendance_threshold_pct, a.status, a.cancelled_reason, a.certificates_issued_at, a.created_by, a.created_at, a.updated_at, a.deleted_at, c.key as category_key, c.name as category_name,
  (select count(*) from activity_registrations r
    where r.activity_id = a.id and r.status <> 'cancelled') as registration_count
from activities a
join activity_categories c on c.id = a.category_id
where a.deleted_at is null
  and a.status = any($1::text[])
  and ($2::uuid is null or a.category_id = $2::uuid)
  and (
    case when $3::boolean
      then a.ends_at >= now()
      else a.ends_at < now()
    end
  )
  and (
    $4::timestamptz is null
    or (
      case when $3::boolean
        then (a.starts_at, a.id) > ($4::timestamptz, $5::uuid)
        else (a.starts_at, a.id) < ($4::timestamptz, $5::uuid)
      end
    )
  )
order by
  case when $3::boolean then a.starts_at end asc,
  case when $3::boolean then a.id end asc,
  case when not $3::boolean then a.starts_at end desc,
  case when not $3::boolean then a.id end desc
limit $6
`

type ListActivitiesParams struct {
	Statuses       []string           `json:"statuses"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	Upcoming       bool               `json:"upcoming"`
	CursorStartsAt pgtype.Timestamptz `json:"cursor_starts_at"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	RowLimit       int32              `json:"row_limit"`
}

type ListActivitiesRow struct {
	ID                     uuid.UUID          `json:"id"`
	CategoryID             uuid.UUID          `json:"category_id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	LocationName           string             `json:"location_name"`
	LocationAddress        string             `json:"location_address"`
	StartsAt               pgtype.Timestamptz `json:"starts_at"`
	EndsAt                 pgtype.Timestamptz `json:"ends_at"`
	RegistrationOpensAt    pgtype.Timestamptz `json:"registration_opens_at"`
	RegistrationClosesAt   pgtype.Timestamptz `json:"registration_closes_at"`
	Capacity               pgtype.Int4        `json:"capacity"`
	FeeCents               int32              `json:"fee_cents"`
	Currency               string             `json:"currency"`
	AttendanceThresholdPct int16              `json:"attendance_threshold_pct"`
	Status                 string             `json:"status"`
	CancelledReason        pgtype.Text        `json:"cancelled_reason"`
	CertificatesIssuedAt   pgtype.Timestamptz `json:"certificates_issued_at"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CategoryKey            string             `json:"category_key"`
	CategoryName           string             `json:"category_name"`
	RegistrationCount      int64              `json:"registration_count"`
}

// Keyset pagination atas (starts_at, id) — sama corak dengan ListPosts,
// elak baris terlepas bila dua aktiviti berkongsi timestamp tepat.
// upcoming=true → aktiviti yang belum tamat, isih menaik (paling hampir
// dahulu). upcoming=false → yang dah tamat, isih menurun.
func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listActivities,
		arg.Statuses,
		arg.CategoryID,
		arg.Upcoming,
		arg.CursorStartsAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesRow
	for rows.Next() {
		var i ListActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.LocationName,
			&i.LocationAddress,
			&i.StartsAt,
			&i.EndsAt,
			&i.RegistrationOpensAt,
			&i.RegistrationClosesAt,
			&i.Capacity,
			&i.FeeCents,
			&i.Currency,
			&i.AttendanceThresholdPct,
			&i.Status,
			&i.CancelledReason,
			&i.CertificatesIssuedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryKey,
			&i.CategoryName,
			&i.RegistrationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityCategories = `-- name: ListActivityCategories :many
select id, key, name, sort_order, is_active, created_at from activity_categories
where is_active = true
order by sort_order, name
`

func (q *Queries) ListActivityCategories(ctx context.Context) ([]ActivityCategory, error) {
	rows, err := q.db.Query(ctx, listActivityCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityCategory
	for rows.Next() {
		var i ActivityCategory
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitySessions = `-- name: ListActivitySessions :many
select id, activity_id, seq, title, starts_at, ends_at from activity_sessions where activity_id = $1 order by seq
`

func (q *Queries) ListActivitySessions(ctx context.Context, activityID uuid.UUID) ([]ActivitySession, error) {
	rows, err := q.db.Query(ctx, listActivitySessions, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivitySession
	for rows.Next() {
		var i ActivitySession
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Seq,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitySessionsByIDs = `-- name: ListActivitySessionsByIDs :many
select id, activity_id, seq, title, starts_at, ends_at from activity_sessions where activity_id = any($1::uuid[]) order by activity_id, seq
`

func (q *Queries) ListActivitySessionsByIDs(ctx context.Context, activityIds []uuid.UUID) ([]ActivitySession, error) {
	rows, err := q.db.Query(ctx, listActivitySessionsByIDs, activityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivitySession
	for rows.Next() {
		var i ActivitySession
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Seq,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeActivityWindow = `-- name: RecomputeActivityWindow :exec
update activities a set
  starts_at = s.min_start,
  ends_at = s.max_end,
  updated_at = now()
from (
  select min(starts_at) as min_start, max(ends_at) as max_end
  from activity_sessions where activity_id = $1
) s
where a.id = $1 and s.min_start is not null
`

// Menjaga invarian denormalisasi. SATU tempat yang menulis starts_at/ends_at
// selepas cipta — dipanggil dalam transaksi yang sama dengan setiap
// perubahan set sesi.
func (q *Queries) RecomputeActivityWindow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recomputeActivityWindow, id)
	return err
}

const setActivityCertificatesIssuedAt = `-- name: SetActivityCertificatesIssuedAt :exec
update activities set certificates_issued_at = now(), updated_at = now()
where id = $1
`

func (q *Queries) SetActivityCertificatesIssuedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setActivityCertificatesIssuedAt, id)
	return err
}

const setActivityStatus = `-- name: SetActivityStatus :one
update activities set status = $2, cancelled_reason = $3, updated_at = now()
where id = $1 and deleted_at is null
returning id, category_id, title, description, location_name, location_address, starts_at, ends_at, registration_opens_at, registration_closes_at, capacity, fee_cents, currency, attendance_threshold_pct, status, cancelled_reason, certificates_issued_at, created_by, created_at, updated_at, deleted_at
`

type SetActivityStatusParams struct {
	ID              uuid.UUID   `json:"id"`
	Status          string      `json:"status"`
	CancelledReason pgtype.Text `json:"cancelled_reason"`
}

func (q *Queries) SetActivityStatus(ctx context.Context, arg SetActivityStatusParams) (Activity, error) {
	row := q.db.QueryRow(ctx, setActivityStatus, arg.ID, arg.Status, arg.CancelledReason)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.Capacity,
		&i.FeeCents,
		&i.Currency,
		&i.AttendanceThresholdPct,
		&i.Status,
		&i.CancelledReason,
		&i.CertificatesIssuedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateActivity = `-- name: UpdateActivity :one
update activities set
  category_id = $2, title = $3, description = $4,
  location_name = $5, location_address = $6,
  registration_opens_at = $7, registration_closes_at = $8,
  capacity = $9, fee_cents = $10, attendance_threshold_pct = $11,
  updated_at = now()
where id = $1 and deleted_at is null
returning id, category_id, title, description, location_name, location_address, starts_at, ends_at, registration_opens_at, registration_closes_at, capacity, fee_cents, currency, attendance_threshold_pct, status, cancelled_reason, certificates_issued_at, created_by, created_at, updated_at, deleted_at
`

type UpdateActivityParams struct {
	ID                     uuid.UUID          `json:"id"`
	CategoryID             uuid.UUID          `json:"category_id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	LocationName           string             `json:"location_name"`
	LocationAddress        string             `json:"location_address"`
	RegistrationOpensAt    pgtype.Timestamptz `json:"registration_opens_at"`
	RegistrationClosesAt   pgtype.Timestamptz `json:"registration_closes_at"`
	Capacity               pgtype.Int4        `json:"capacity"`
	FeeCents               int32              `json:"fee_cents"`
	AttendanceThresholdPct int16              `json:"attendance_threshold_pct"`
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivity,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.LocationName,
		arg.LocationAddress,
		arg.RegistrationOpensAt,
		arg.RegistrationClosesAt,
		arg.Capacity,
		arg.FeeCents,
		arg.AttendanceThresholdPct,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.Capacity,
		&i.FeeCents,
		&i.Currency,
		&i.AttendanceThresholdPct,
		&i.Status,
		&i.CancelledReason,
		&i.CertificatesIssuedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
