// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_certificates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCertificate = `-- name: CreateCertificate :one
insert into activity_certificates (
  activity_id, user_id, serial, verify_token,
  recipient_name, activity_title, activity_date
) values ($1, $2, $3, $4, $5, $6, $7)
on conflict (activity_id, user_id) do nothing
returning id, activity_id, user_id, serial, verify_token, recipient_name, activity_title, activity_date, issued_at, r2_key, revoked_at, revoked_reason
`

type CreateCertificateParams struct {
	ActivityID    uuid.UUID   `json:"activity_id"`
	UserID        uuid.UUID   `json:"user_id"`
	Serial        string      `json:"serial"`
	VerifyToken   string      `json:"verify_token"`
	RecipientName string      `json:"recipient_name"`
	ActivityTitle string      `json:"activity_title"`
	ActivityDate  pgtype.Date `json:"activity_date"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (ActivityCertificate, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.ActivityID,
		arg.UserID,
		arg.Serial,
		arg.VerifyToken,
		arg.RecipientName,
		arg.ActivityTitle,
		arg.ActivityDate,
	)
	var i ActivityCertificate
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Serial,
		&i.VerifyToken,
		&i.RecipientName,
		&i.ActivityTitle,
		&i.ActivityDate,
		&i.IssuedAt,
		&i.R2Key,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
select id, activity_id, user_id, serial, verify_token, recipient_name, activity_title, activity_date, issued_at, r2_key, revoked_at, revoked_reason from activity_certificates where id = $1
`

func (q *Queries) GetCertificateByID(ctx context.Context, id uuid.UUID) (ActivityCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i ActivityCertificate
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Serial,
		&i.VerifyToken,
		&i.RecipientName,
		&i.ActivityTitle,
		&i.ActivityDate,
		&i.IssuedAt,
		&i.R2Key,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getCertificateByVerifyToken = `-- name: GetCertificateByVerifyToken :one
select id, activity_id, user_id, serial, verify_token, recipient_name, activity_title, activity_date, issued_at, r2_key, revoked_at, revoked_reason from activity_certificates where verify_token = $1
`

func (q *Queries) GetCertificateByVerifyToken(ctx context.Context, verifyToken string) (ActivityCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByVerifyToken, verifyToken)
	var i ActivityCertificate
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Serial,
		&i.VerifyToken,
		&i.RecipientName,
		&i.ActivityTitle,
		&i.ActivityDate,
		&i.IssuedAt,
		&i.R2Key,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const listCertificatesByActivity = `-- name: ListCertificatesByActivity :many
select id, activity_id, user_id, serial, verify_token, recipient_name, activity_title, activity_date, issued_at, r2_key, revoked_at, revoked_reason from activity_certificates where activity_id = $1 order by serial
`

func (q *Queries) ListCertificatesByActivity(ctx context.Context, activityID uuid.UUID) ([]ActivityCertificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByActivity, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityCertificate
	for rows.Next() {
		var i ActivityCertificate
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Serial,
			&i.VerifyToken,
			&i.RecipientName,
			&i.ActivityTitle,
			&i.ActivityDate,
			&i.IssuedAt,
			&i.R2Key,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesPendingFile = `-- name: ListCertificatesPendingFile :many
select id, activity_id, user_id, serial, verify_token, recipient_name, activity_title, activity_date, issued_at, r2_key, revoked_at, revoked_reason from activity_certificates
where activity_id = $1 and r2_key is null and revoked_at is null
`

// Fasa 2 penerbitan menyambung dari sini. Baris tanpa r2_key ialah kerja
// yang belum siap, bukan ralat.
func (q *Queries) ListCertificatesPendingFile(ctx context.Context, activityID uuid.UUID) ([]ActivityCertificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesPendingFile, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityCertificate
	for rows.Next() {
		var i ActivityCertificate
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Serial,
			&i.VerifyToken,
			&i.RecipientName,
			&i.ActivityTitle,
			&i.ActivityDate,
			&i.IssuedAt,
			&i.R2Key,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleForCertificate = `-- name: ListEligibleForCertificate :many
select r.id as registration_id, r.user_id,
  coalesce(pr.display_name, pr.member_id) as display_name,
  (select count(*) from activity_attendances at where at.registration_id = r.id) as attended
from activity_registrations r
join profiles pr on pr.user_id = r.user_id
join activities a on a.id = r.activity_id
where r.activity_id = $1
  and r.status = 'registered'
  and (a.fee_cents = 0 or r.payment_status = 'paid')
order by coalesce(pr.display_name, pr.member_id)
`

type ListEligibleForCertificateRow struct {
	RegistrationID uuid.UUID `json:"registration_id"`
	UserID         uuid.UUID `json:"user_id"`
	DisplayName    string    `json:"display_name"`
	Attended       int64     `json:"attended"`
}

// Server mengira sendiri siapa layak — management tidak menyenaraikan.
// Klausa payment_status kekal walaupun payment belum diintegrasikan:
// fee_cents sentiasa 0 buat masa ini, jadi ia sentiasa benar.
// display_name boleh null, tapi recipient_name pada sijil not null —
// jatuh balik ke member_id supaya ahli tanpa nama paparan tetap dapat
// nama yang boleh dicetak.
func (q *Queries) ListEligibleForCertificate(ctx context.Context, activityID uuid.UUID) ([]ListEligibleForCertificateRow, error) {
	rows, err := q.db.Query(ctx, listEligibleForCertificate, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleForCertificateRow
	for rows.Next() {
		var i ListEligibleForCertificateRow
		if err := rows.Scan(
			&i.RegistrationID,
			&i.UserID,
			&i.DisplayName,
			&i.Attended,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCertificates = `-- name: ListMyCertificates :many
select ac.id, ac.activity_id, ac.user_id, ac.serial, ac.verify_token, ac.recipient_name, ac.activity_title, ac.activity_date, ac.issued_at, ac.r2_key, ac.revoked_at, ac.revoked_reason, c.name as category_name
from activity_certificates ac
join activities a on a.id = ac.activity_id
join activity_categories c on c.id = a.category_id
where ac.user_id = $1 and ac.revoked_at is null
order by ac.issued_at desc
`

type ListMyCertificatesRow struct {
	ID            uuid.UUID          `json:"id"`
	ActivityID    uuid.UUID          `json:"activity_id"`
	UserID        uuid.UUID          `json:"user_id"`
	Serial        string             `json:"serial"`
	VerifyToken   string             `json:"verify_token"`
	RecipientName string             `json:"recipient_name"`
	ActivityTitle string             `json:"activity_title"`
	ActivityDate  pgtype.Date        `json:"activity_date"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	R2Key         pgtype.Text        `json:"r2_key"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	CategoryName  string             `json:"category_name"`
}

func (q *Queries) ListMyCertificates(ctx context.Context, userID uuid.UUID) ([]ListMyCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listMyCertificates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyCertificatesRow
	for rows.Next() {
		var i ListMyCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Serial,
			&i.VerifyToken,
			&i.RecipientName,
			&i.ActivityTitle,
			&i.ActivityDate,
			&i.IssuedAt,
			&i.R2Key,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCertificate = `-- name: RevokeCertificate :one
update activity_certificates
set revoked_at = now(), revoked_reason = $2
where id = $1 and revoked_at is null
returning id, activity_id, user_id, serial, verify_token, recipient_name, activity_title, activity_date, issued_at, r2_key, revoked_at, revoked_reason
`

type RevokeCertificateParams struct {
	ID            uuid.UUID   `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (ActivityCertificate, error) {
	row := q.db.QueryRow(ctx, revokeCertificate, arg.ID, arg.RevokedReason)
	var i ActivityCertificate
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Serial,
		&i.VerifyToken,
		&i.RecipientName,
		&i.ActivityTitle,
		&i.ActivityDate,
		&i.IssuedAt,
		&i.R2Key,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const setCertificateR2Key = `-- name: SetCertificateR2Key :exec
update activity_certificates set r2_key = $2 where id = $1
`

type SetCertificateR2KeyParams struct {
	ID    uuid.UUID   `json:"id"`
	R2Key pgtype.Text `json:"r2_key"`
}

func (q *Queries) SetCertificateR2Key(ctx context.Context, arg SetCertificateR2KeyParams) error {
	_, err := q.db.Exec(ctx, setCertificateR2Key, arg.ID, arg.R2Key)
	return err
}
