// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_registrations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRegistration = `-- name: CancelRegistration :one
update activity_registrations
set status = 'cancelled', cancelled_at = now()
where activity_id = $1 and user_id = $2 and status <> 'cancelled'
returning id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at
`

type CancelRegistrationParams struct {
	ActivityID uuid.UUID `json:"activity_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) CancelRegistration(ctx context.Context, arg CancelRegistrationParams) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, cancelRegistration, arg.ActivityID, arg.UserID)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentRef,
		&i.CheckinToken,
		&i.RegisteredAt,
		&i.CancelledAt,
	)
	return i, err
}

const cancelStaleUnpaidBills = `-- name: CancelStaleUnpaidBills :many
update activity_registrations
set status = 'cancelled', cancelled_at = now()
where payment_status = 'pending' and status <> 'cancelled'
  and payment_ref is not null and registered_at < $1
returning id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at
`

// Batal pendaftaran yang DAH cuba checkout (payment_ref wujud, bil
// ToyyibPay sebenar dicipta) selepas cutoff PANJANG — sengaja lain drpd
// CancelStaleUnstartedPayments.
//
// Kenapa cutoff PANJANG di sini: bil ToyyibPay yang dah dicipta boleh
// disahkan bila-bila masa oleh webhook (FPX/bank kadang ambil lebih 45
// minit — pembayar boleh tinggalkan app lama sebelum sambung semula ke
// laman bank). Kalau baris ni dibatal pada cutoff PENDEK yang sama
// macam "tak pernah cuba", webhook yang tiba LEPAS itu (UPDATE ...
// WHERE payment_ref = $1 AND payment_status <> 'paid', TIADA
// `status <> 'cancelled'` guard dengan sengaja — lihat komen
// UpdateRegistrationPaymentStatusByPaymentRef) akan tetap tanda
// payment_status='paid' atas baris yang `status='cancelled'` — ahli
// dah BAYAR tapi slotnya HILANG, tiada jejak melainkan seseorang cari
// baris cancelled+paid secara manual. Cutoff panjang kurangkan
// kebarangkalian tetingkap lumba ni secara drastik (bukan hapuskan
// 100% — itu perlukan reka bentuk lebih kompleks, dianggap tak
// berbaloi buat masa ini: risiko kapasiti terikat lebih lama jauh
// lebih kecil drpd risiko kehilangan bayaran ahli).
func (q *Queries) CancelStaleUnpaidBills(ctx context.Context, registeredAt pgtype.Timestamptz) ([]ActivityRegistration, error) {
	rows, err := q.db.Query(ctx, cancelStaleUnpaidBills, registeredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRegistration
	for rows.Next() {
		var i ActivityRegistration
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentRef,
			&i.CheckinToken,
			&i.RegisteredAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelStaleUnstartedPayments = `-- name: CancelStaleUnstartedPayments :many
update activity_registrations
set status = 'cancelled', cancelled_at = now()
where payment_status = 'pending' and status <> 'cancelled'
  and payment_ref is null and registered_at < $1
returning id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at
`

// Batal pendaftaran berbayar yang ahli TAK PERNAH cuba checkout
// (payment_ref masih NULL — tiada bil ToyyibPay pernah dicipta) selepas
// cutoff PENDEK. Selamat dibatal cepat: tiada webhook akan datang untuk
// baris ni sebab tiada bil wujud langsung.
//
// `and status <> 'cancelled'` — tanpa ni, baris yang DAH dibatal pusingan
// sebelum kena UPDATE semula setiap 15 minit selama-lamanya, tulis ganti
// `cancelled_at` (rosakkan jejak audit "bila SEBENAR ia dibatal") dan
// kembungkan bilangan baris dilaporkan log tanpa sebab.
func (q *Queries) CancelStaleUnstartedPayments(ctx context.Context, registeredAt pgtype.Timestamptz) ([]ActivityRegistration, error) {
	rows, err := q.db.Query(ctx, cancelStaleUnstartedPayments, registeredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRegistration
	for rows.Next() {
		var i ActivityRegistration
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentRef,
			&i.CheckinToken,
			&i.RegisteredAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveRegistrations = `-- name: CountActiveRegistrations :one
select count(*) from activity_registrations
where activity_id = $1 and status <> 'cancelled'
`

func (q *Queries) CountActiveRegistrations(ctx context.Context, activityID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRegistrations, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegistration = `-- name: CreateRegistration :one
insert into activity_registrations (activity_id, user_id, status, payment_status, checkin_token)
values ($1, $2, $3, $4, $5)
returning id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at
`

type CreateRegistrationParams struct {
	ActivityID    uuid.UUID `json:"activity_id"`
	UserID        uuid.UUID `json:"user_id"`
	Status        string    `json:"status"`
	PaymentStatus string    `json:"payment_status"`
	CheckinToken  string    `json:"checkin_token"`
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, createRegistration,
		arg.ActivityID,
		arg.UserID,
		arg.Status,
		arg.PaymentStatus,
		arg.CheckinToken,
	)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentRef,
		&i.CheckinToken,
		&i.RegisteredAt,
		&i.CancelledAt,
	)
	return i, err
}

const getRegistrationByActivityAndUser = `-- name: GetRegistrationByActivityAndUser :one
select id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at from activity_registrations
where activity_id = $1 and user_id = $2 and status <> 'cancelled'
`

type GetRegistrationByActivityAndUserParams struct {
	ActivityID uuid.UUID `json:"activity_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRegistrationByActivityAndUser(ctx context.Context, arg GetRegistrationByActivityAndUserParams) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByActivityAndUser, arg.ActivityID, arg.UserID)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentRef,
		&i.CheckinToken,
		&i.RegisteredAt,
		&i.CancelledAt,
	)
	return i, err
}

const getRegistrationByCheckinToken = `-- name: GetRegistrationByCheckinToken :one
select id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at from activity_registrations
where checkin_token = $1 and status <> 'cancelled'
`

func (q *Queries) GetRegistrationByCheckinToken(ctx context.Context, checkinToken string) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByCheckinToken, checkinToken)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentRef,
		&i.CheckinToken,
		&i.RegisteredAt,
		&i.CancelledAt,
	)
	return i, err
}

const getRegistrationByID = `-- name: GetRegistrationByID :one
select id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at from activity_registrations where id = $1
`

func (q *Queries) GetRegistrationByID(ctx context.Context, id uuid.UUID) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByID, id)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentRef,
		&i.CheckinToken,
		&i.RegisteredAt,
		&i.CancelledAt,
	)
	return i, err
}

const listMyActivityPayments = `-- name: ListMyActivityPayments :many
select r.id, r.activity_id, r.user_id, r.status, r.payment_status, r.payment_ref, r.checkin_token, r.registered_at, r.cancelled_at, a.title, a.fee_cents, a.currency, a.starts_at
from activity_registrations r
join activities a on a.id = r.activity_id
where r.user_id = $1 and r.payment_status <> 'not_required'
order by r.registered_at desc
`

type ListMyActivityPaymentsRow struct {
	ID            uuid.UUID          `json:"id"`
	ActivityID    uuid.UUID          `json:"activity_id"`
	UserID        uuid.UUID          `json:"user_id"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	PaymentRef    pgtype.Text        `json:"payment_ref"`
	CheckinToken  string             `json:"checkin_token"`
	RegisteredAt  pgtype.Timestamptz `json:"registered_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	Title         string             `json:"title"`
	FeeCents      int32              `json:"fee_cents"`
	Currency      string             `json:"currency"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
}

// Sejarah yuran aktiviti seorang ahli — TERMASUK pendaftaran yang telah
// dibatalkan (beza sengaja drpd ListMyRegistrations di atas, yang tolak
// baris 'cancelled' sebab tab "Aktiviti Saya" tu untuk pendaftaran AKTIF
// sahaja): sejarah bayaran patut tetap tunjuk percubaan yang gagal/tak
// sempat dibayar sebelum disapu, bukan senyap hilang.
func (q *Queries) ListMyActivityPayments(ctx context.Context, userID uuid.UUID) ([]ListMyActivityPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listMyActivityPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyActivityPaymentsRow
	for rows.Next() {
		var i ListMyActivityPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentRef,
			&i.CheckinToken,
			&i.RegisteredAt,
			&i.CancelledAt,
			&i.Title,
			&i.FeeCents,
			&i.Currency,
			&i.StartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyRegistrations = `-- name: ListMyRegistrations :many
select r.id, r.activity_id, r.user_id, r.status, r.payment_status, r.payment_ref, r.checkin_token, r.registered_at, r.cancelled_at, a.title, a.starts_at, a.ends_at, a.status as activity_status,
  c.name as category_name
from activity_registrations r
join activities a on a.id = r.activity_id
join activity_categories c on c.id = a.category_id
where r.user_id = $1 and r.status <> 'cancelled' and a.deleted_at is null
order by a.starts_at desc
`

type ListMyRegistrationsRow struct {
	ID             uuid.UUID          `json:"id"`
	ActivityID     uuid.UUID          `json:"activity_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Status         string             `json:"status"`
	PaymentStatus  string             `json:"payment_status"`
	PaymentRef     pgtype.Text        `json:"payment_ref"`
	CheckinToken   string             `json:"checkin_token"`
	RegisteredAt   pgtype.Timestamptz `json:"registered_at"`
	CancelledAt    pgtype.Timestamptz `json:"cancelled_at"`
	Title          string             `json:"title"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	ActivityStatus string             `json:"activity_status"`
	CategoryName   string             `json:"category_name"`
}

func (q *Queries) ListMyRegistrations(ctx context.Context, userID uuid.UUID) ([]ListMyRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listMyRegistrations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyRegistrationsRow
	for rows.Next() {
		var i ListMyRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentRef,
			&i.CheckinToken,
			&i.RegisteredAt,
			&i.CancelledAt,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.ActivityStatus,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingActivityRegistrationsOlderThan = `-- name: ListPendingActivityRegistrationsOlderThan :many
select id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at from activity_registrations
where payment_status = 'pending' and payment_ref is not null and registered_at < $1
order by registered_at
`

// Baris 'pending' YANG DAH cuba checkout (payment_ref wujud) dan dah
// cukup umur untuk layak disemak semula terus pada gateway
// (internal/paymentreconcile) — padanan `CancelStaleUnpaidBills` dari
// segi skop (payment_ref is not null), tapi cutoff jauh lebih pendek
// (reconcile MEMBETULKAN state, bukan membatalkan secara musnah, jadi
// semak awal selamat — lihat internal/paymentreconcile untuk alasan
// penuh). Baris `payment_ref is null` (tak pernah cuba checkout) dilangkau
// — tiada apa nak disemak pada gateway untuk baris begitu.
func (q *Queries) ListPendingActivityRegistrationsOlderThan(ctx context.Context, registeredAt pgtype.Timestamptz) ([]ActivityRegistration, error) {
	rows, err := q.db.Query(ctx, listPendingActivityRegistrationsOlderThan, registeredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityRegistration
	for rows.Next() {
		var i ActivityRegistration
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentRef,
			&i.CheckinToken,
			&i.RegisteredAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationsByActivity = `-- name: ListRegistrationsByActivity :many
select r.id, r.activity_id, r.user_id, r.status, r.payment_status, r.payment_ref, r.checkin_token, r.registered_at, r.cancelled_at, pr.member_id, pr.display_name, pr.avatar_r2_key,
  coalesce(att.session_ids, '{}')::uuid[] as attended_session_ids
from activity_registrations r
join profiles pr on pr.user_id = r.user_id
left join (
  select at.registration_id, array_agg(at.session_id order by s.seq) as session_ids
  from activity_attendances at
  join activity_sessions s on s.id = at.session_id
  where s.activity_id = $1
  group by at.registration_id
) att on att.registration_id = r.id
where r.activity_id = $1 and r.status <> 'cancelled'
order by pr.display_name
`

type ListRegistrationsByActivityRow struct {
	ID                 uuid.UUID          `json:"id"`
	ActivityID         uuid.UUID          `json:"activity_id"`
	UserID             uuid.UUID          `json:"user_id"`
	Status             string             `json:"status"`
	PaymentStatus      string             `json:"payment_status"`
	PaymentRef         pgtype.Text        `json:"payment_ref"`
	CheckinToken       string             `json:"checkin_token"`
	RegisteredAt       pgtype.Timestamptz `json:"registered_at"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	MemberID           string             `json:"member_id"`
	DisplayName        pgtype.Text        `json:"display_name"`
	AvatarR2Key        pgtype.Text        `json:"avatar_r2_key"`
	AttendedSessionIds []uuid.UUID        `json:"attended_session_ids"`
}

// attended_session_ids menjawab "sesi mana pendaftaran ini sudah hadir?" —
// skrin kehadiran pengurusan menyemai suisnya daripada medan ini. Satu
// boolean per peserta tidak mencukupi: kehadiran ialah per-sesi.
//
// Agregat dikira SEKALI dalam subkueri berkumpulan, bukan satu kueri per
// pendaftaran; senarai ini dibaca dengan seluruh peserta sekali gus, jadi
// N+1 di sini bermakna satu perjalanan DB bagi setiap ahli.
//
// coalesce(..., '{}') penting: left join memberi NULL untuk pendaftaran
// tanpa kehadiran, dan NULL bersiri sebagai `null` dalam JSON. Klien yang
// memanggil .map atasnya terhempas — [] ialah kontrak.
func (q *Queries) ListRegistrationsByActivity(ctx context.Context, activityID uuid.UUID) ([]ListRegistrationsByActivityRow, error) {
	rows, err := q.db.Query(ctx, listRegistrationsByActivity, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistrationsByActivityRow
	for rows.Next() {
		var i ListRegistrationsByActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentRef,
			&i.CheckinToken,
			&i.RegisteredAt,
			&i.CancelledAt,
			&i.MemberID,
			&i.DisplayName,
			&i.AvatarR2Key,
			&i.AttendedSessionIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActivityForRegistration = `-- name: LockActivityForRegistration :one
select id, category_id, title, description, location_name, location_address, starts_at, ends_at, registration_opens_at, registration_closes_at, capacity, fee_cents, currency, attendance_threshold_pct, status, cancelled_reason, certificates_issued_at, created_by, created_at, updated_at, deleted_at from activities where id = $1 and deleted_at is null for update
`

// `for update` atas baris aktiviti — ini yang menyerikan pendaftaran
// serentak supaya kiraan kapasiti tak boleh basi antara baca dan tulis.
func (q *Queries) LockActivityForRegistration(ctx context.Context, id uuid.UUID) (Activity, error) {
	row := q.db.QueryRow(ctx, lockActivityForRegistration, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationAddress,
		&i.StartsAt,
		&i.EndsAt,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.Capacity,
		&i.FeeCents,
		&i.Currency,
		&i.AttendanceThresholdPct,
		&i.Status,
		&i.CancelledReason,
		&i.CertificatesIssuedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setRegistrationPaymentRef = `-- name: SetRegistrationPaymentRef :one
update activity_registrations
set payment_ref = $2
where id = $1
returning id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at
`

type SetRegistrationPaymentRefParams struct {
	ID         uuid.UUID   `json:"id"`
	PaymentRef pgtype.Text `json:"payment_ref"`
}

// Simpan bill code ToyyibPay pada pendaftaran sedia ada, dipanggil sebaik
// createBill berjaya semasa checkout yuran aktiviti.
func (q *Queries) SetRegistrationPaymentRef(ctx context.Context, arg SetRegistrationPaymentRefParams) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, setRegistrationPaymentRef, arg.ID, arg.PaymentRef)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentRef,
		&i.CheckinToken,
		&i.RegisteredAt,
		&i.CancelledAt,
	)
	return i, err
}

const updateRegistrationPaymentStatusByPaymentRef = `-- name: UpdateRegistrationPaymentStatusByPaymentRef :one
update activity_registrations
set payment_status = $2
where payment_ref = $1 and payment_status <> 'paid'
returning id, activity_id, user_id, status, payment_status, payment_ref, checkin_token, registered_at, cancelled_at
`

type UpdateRegistrationPaymentStatusByPaymentRefParams struct {
	PaymentRef    pgtype.Text `json:"payment_ref"`
	PaymentStatus string      `json:"payment_status"`
}

// Padanan UpdateRegistrationPaymentStatusByGatewayRef (registration_payments)
// tapi bagi activity_registrations: kunci carian payment_ref (bill code),
// bukan (gateway, gateway_ref) berasingan sebab jadual ni tak simpan lajur
// gateway berasingan (satu gateway sahaja buat masa ini, ToyyibPay).
// Kekang `payment_status <> 'paid'` idempotent — 'paid' ialah keadaan
// terminal, replay webhook lepas tu ialah no-op.
//
// SENGAJA TIADA `and status <> 'cancelled'`: kalau baris ni dah dibatal
// (CancelStaleUnpaidBills) tapi webhook confirm lambat tiba, UPDATE ni
// MASIH akan tanda payment_status='paid' walaupun status='cancelled' —
// keadaan cancelled+paid yang ganjil, tapi SENGAJA supaya boleh dikesan
// (handler Go log ERROR bila ini berlaku, lihat activity_registration_payment.go)
// bukan senyap hilang. Kalau guard `status<>'cancelled'` ditambah di sini,
// UPDATE gagal (0 baris), pgx.ErrNoRows dianggap "replay biasa", dan
// kesnya jadi kelihatan macam tiada apa berlaku — walhal ahli dah bayar.
func (q *Queries) UpdateRegistrationPaymentStatusByPaymentRef(ctx context.Context, arg UpdateRegistrationPaymentStatusByPaymentRefParams) (ActivityRegistration, error) {
	row := q.db.QueryRow(ctx, updateRegistrationPaymentStatusByPaymentRef, arg.PaymentRef, arg.PaymentStatus)
	var i ActivityRegistration
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentRef,
		&i.CheckinToken,
		&i.RegisteredAt,
		&i.CancelledAt,
	)
	return i, err
}
