// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_attendances.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAttendanceByRegistration = `-- name: CountAttendanceByRegistration :one
select count(*) from activity_attendances where registration_id = $1
`

func (q *Queries) CountAttendanceByRegistration(ctx context.Context, registrationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttendanceByRegistration, registrationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAttendance = `-- name: DeleteAttendance :execrows
delete from activity_attendances
where registration_id = $1 and session_id = $2
`

type DeleteAttendanceParams struct {
	RegistrationID uuid.UUID `json:"registration_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

func (q *Queries) DeleteAttendance(ctx context.Context, arg DeleteAttendanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttendance, arg.RegistrationID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttendance = `-- name: GetAttendance :one
select id, registration_id, session_id, method, marked_by, checked_in_at from activity_attendances
where registration_id = $1 and session_id = $2
`

type GetAttendanceParams struct {
	RegistrationID uuid.UUID `json:"registration_id"`
	SessionID      uuid.UUID `json:"session_id"`
}

func (q *Queries) GetAttendance(ctx context.Context, arg GetAttendanceParams) (ActivityAttendance, error) {
	row := q.db.QueryRow(ctx, getAttendance, arg.RegistrationID, arg.SessionID)
	var i ActivityAttendance
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.SessionID,
		&i.Method,
		&i.MarkedBy,
		&i.CheckedInAt,
	)
	return i, err
}

const listAttendanceByActivity = `-- name: ListAttendanceByActivity :many
select at.id, at.registration_id, at.session_id, at.method, at.marked_by, at.checked_in_at from activity_attendances at
join activity_sessions s on s.id = at.session_id
where s.activity_id = $1
`

func (q *Queries) ListAttendanceByActivity(ctx context.Context, activityID uuid.UUID) ([]ActivityAttendance, error) {
	rows, err := q.db.Query(ctx, listAttendanceByActivity, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityAttendance
	for rows.Next() {
		var i ActivityAttendance
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.SessionID,
			&i.Method,
			&i.MarkedBy,
			&i.CheckedInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttendance = `-- name: MarkAttendance :one
insert into activity_attendances (registration_id, session_id, method, marked_by)
values ($1, $2, $3, $4)
on conflict (registration_id, session_id) do nothing
returning id, registration_id, session_id, method, marked_by, checked_in_at
`

type MarkAttendanceParams struct {
	RegistrationID uuid.UUID   `json:"registration_id"`
	SessionID      uuid.UUID   `json:"session_id"`
	Method         string      `json:"method"`
	MarkedBy       pgtype.UUID `json:"marked_by"`
}

// on conflict do nothing + returning: imbas kedua QR yang sama bukan ralat,
// ia cuma tiada kerja. Handler membezakan "baharu" daripada "sudah ada"
// melalui sama ada baris dipulangkan.
func (q *Queries) MarkAttendance(ctx context.Context, arg MarkAttendanceParams) (ActivityAttendance, error) {
	row := q.db.QueryRow(ctx, markAttendance,
		arg.RegistrationID,
		arg.SessionID,
		arg.Method,
		arg.MarkedBy,
	)
	var i ActivityAttendance
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.SessionID,
		&i.Method,
		&i.MarkedBy,
		&i.CheckedInAt,
	)
	return i, err
}
