// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
insert into audit_logs (
  entity_type, entity_id, action,
  actor_id, actor_member_id, actor_role_key,
  changed_fields, old_values, new_values,
  ip_address, user_agent
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAuditLogParams struct {
	EntityType    string      `json:"entity_type"`
	EntityID      uuid.UUID   `json:"entity_id"`
	Action        string      `json:"action"`
	ActorID       pgtype.UUID `json:"actor_id"`
	ActorMemberID pgtype.Text `json:"actor_member_id"`
	ActorRoleKey  pgtype.Text `json:"actor_role_key"`
	ChangedFields []string    `json:"changed_fields"`
	OldValues     []byte      `json:"old_values"`
	NewValues     []byte      `json:"new_values"`
	IpAddress     pgtype.Text `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.ActorID,
		arg.ActorMemberID,
		arg.ActorRoleKey,
		arg.ChangedFields,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const deleteAuditLogsBefore = `-- name: DeleteAuditLogsBefore :execrows
delete from audit_logs where created_at < $1
`

// Pruning polisi simpanan (lihat internal/retention).
func (q *Queries) DeleteAuditLogsBefore(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditLogsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
select id, entity_type, entity_id, action, actor_id, actor_member_id, actor_role_key, changed_fields, old_values, new_values, ip_address, user_agent, created_at from audit_logs
where ($1::text is null or entity_type = $1::text)
  and ($2::text is null or action = $2::text)
  and ($3::uuid is null or actor_id = $3::uuid)
  and ($4::bigint is null or id < $4::bigint)
order by id desc
limit $5
`

type ListAuditLogsParams struct {
	EntityType pgtype.Text `json:"entity_type"`
	Action     pgtype.Text `json:"action"`
	ActorID    pgtype.UUID `json:"actor_id"`
	BeforeID   pgtype.Int8 `json:"before_id"`
	RowLimit   int32       `json:"row_limit"`
}

// Feed audit global dengan tapisan pilihan. Pagination keyset guna
// `before_id` (bukan OFFSET) — stabil walaupun baris baharu masuk
// semasa pengguna membelek.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.EntityType,
		arg.Action,
		arg.ActorID,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorID,
			&i.ActorMemberID,
			&i.ActorRoleKey,
			&i.ChangedFields,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
select id, entity_type, entity_id, action, actor_id, actor_member_id, actor_role_key, changed_fields, old_values, new_values, ip_address, user_agent, created_at from audit_logs
where entity_type = $1 and entity_id = $2
order by id desc
limit $3
`

type ListAuditLogsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Limit      int32     `json:"limit"`
}

// Timeline satu entiti (cth semua suntingan pada satu post).
func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorID,
			&i.ActorMemberID,
			&i.ActorRoleKey,
			&i.ChangedFields,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redactAuditLogPIIBefore = `-- name: RedactAuditLogPIIBefore :execrows
update audit_logs
set ip_address = null, user_agent = null
where created_at < $1
  and (ip_address is not null or user_agent is not null)
`

// Buang metadata permintaan daripada catatan lama TANPA memusnahkan
// catatan itu sendiri. Dibenarkan oleh trigger append-only kerana ia
// hanya menetapkan kedua-dua lajur ini kepada NULL — lihat migration
// 20260809180000.
func (q *Queries) RedactAuditLogPIIBefore(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, redactAuditLogPIIBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
