// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocked_email_domains.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBlockedEmailDomain = `-- name: AddBlockedEmailDomain :one
insert into blocked_email_domains (domain, added_by)
values ($1, $2)
on conflict (domain) do nothing
returning domain, added_by, created_at
`

type AddBlockedEmailDomainParams struct {
	Domain  string      `json:"domain"`
	AddedBy pgtype.UUID `json:"added_by"`
}

// `on conflict do nothing` — idempoten, tambah domain yang dah wujud
// bukan ralat (padanan pola ApproveProfile `status <> 'approved'`).
func (q *Queries) AddBlockedEmailDomain(ctx context.Context, arg AddBlockedEmailDomainParams) (BlockedEmailDomain, error) {
	row := q.db.QueryRow(ctx, addBlockedEmailDomain, arg.Domain, arg.AddedBy)
	var i BlockedEmailDomain
	err := row.Scan(&i.Domain, &i.AddedBy, &i.CreatedAt)
	return i, err
}

const isEmailDomainBlocked = `-- name: IsEmailDomainBlocked :one
select exists(select 1 from blocked_email_domains where domain = $1)
`

// Semakan pendaftaran (/auth/register) — pelengkap kpd senarai statik
// terbenam (internal/disposableemail), utk domain tambahan management.
func (q *Queries) IsEmailDomainBlocked(ctx context.Context, domain string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailDomainBlocked, domain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlockedEmailDomains = `-- name: ListBlockedEmailDomains :many
select domain, added_by, created_at from blocked_email_domains order by created_at desc
`

// Skrin pengurusan CRUD domain disekat.
func (q *Queries) ListBlockedEmailDomains(ctx context.Context) ([]BlockedEmailDomain, error) {
	rows, err := q.db.Query(ctx, listBlockedEmailDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedEmailDomain
	for rows.Next() {
		var i BlockedEmailDomain
		if err := rows.Scan(&i.Domain, &i.AddedBy, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBlockedEmailDomain = `-- name: RemoveBlockedEmailDomain :execrows
delete from blocked_email_domains where domain = $1
`

func (q *Queries) RemoveBlockedEmailDomain(ctx context.Context, domain string) (int64, error) {
	result, err := q.db.Exec(ctx, removeBlockedEmailDomain, domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
