// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificate_templates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getActiveCertificateTemplate = `-- name: GetActiveCertificateTemplate :one
select id, name, is_active, primary_color, secondary_color, logo_url, title, subtitle, body_text, issuer_name, signature_name, footer_text, created_at, updated_at
from certificate_templates
where is_active
order by updated_at desc
limit 1
`

func (q *Queries) GetActiveCertificateTemplate(ctx context.Context) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, getActiveCertificateTemplate)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.LogoUrl,
		&i.Title,
		&i.Subtitle,
		&i.BodyText,
		&i.IssuerName,
		&i.SignatureName,
		&i.FooterText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificateTemplate = `-- name: GetCertificateTemplate :one
select id, name, is_active, primary_color, secondary_color, logo_url, title, subtitle, body_text, issuer_name, signature_name, footer_text, created_at, updated_at
from certificate_templates
where id = $1
`

func (q *Queries) GetCertificateTemplate(ctx context.Context, id uuid.UUID) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, getCertificateTemplate, id)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.LogoUrl,
		&i.Title,
		&i.Subtitle,
		&i.BodyText,
		&i.IssuerName,
		&i.SignatureName,
		&i.FooterText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertificateTemplates = `-- name: ListCertificateTemplates :many
select id, name, is_active, primary_color, secondary_color, logo_url, title, subtitle, body_text, issuer_name, signature_name, footer_text, created_at, updated_at
from certificate_templates
order by is_active desc, updated_at desc, name asc
`

func (q *Queries) ListCertificateTemplates(ctx context.Context) ([]CertificateTemplate, error) {
	rows, err := q.db.Query(ctx, listCertificateTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CertificateTemplate
	for rows.Next() {
		var i CertificateTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.PrimaryColor,
			&i.SecondaryColor,
			&i.LogoUrl,
			&i.Title,
			&i.Subtitle,
			&i.BodyText,
			&i.IssuerName,
			&i.SignatureName,
			&i.FooterText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishCertificateTemplate = `-- name: PublishCertificateTemplate :one
with deactivated as (
  update certificate_templates
  set is_active = false, updated_at = now()
  where is_active and id <> $1
)
update certificate_templates
set is_active = true, updated_at = now()
where certificate_templates.id = $1
returning id, name, is_active, primary_color, secondary_color, logo_url, title, subtitle, body_text, issuer_name, signature_name, footer_text, created_at, updated_at
`

func (q *Queries) PublishCertificateTemplate(ctx context.Context, id uuid.UUID) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, publishCertificateTemplate, id)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.LogoUrl,
		&i.Title,
		&i.Subtitle,
		&i.BodyText,
		&i.IssuerName,
		&i.SignatureName,
		&i.FooterText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCertificateTemplate = `-- name: UpdateCertificateTemplate :one
update certificate_templates
set
  name = $2,
  primary_color = $3,
  secondary_color = $4,
  logo_url = $5,
  title = $6,
  subtitle = $7,
  body_text = $8,
  issuer_name = $9,
  signature_name = $10,
  footer_text = $11,
  updated_at = now()
where id = $1
returning id, name, is_active, primary_color, secondary_color, logo_url, title, subtitle, body_text, issuer_name, signature_name, footer_text, created_at, updated_at
`

type UpdateCertificateTemplateParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	PrimaryColor   string    `json:"primary_color"`
	SecondaryColor string    `json:"secondary_color"`
	LogoUrl        string    `json:"logo_url"`
	Title          string    `json:"title"`
	Subtitle       string    `json:"subtitle"`
	BodyText       string    `json:"body_text"`
	IssuerName     string    `json:"issuer_name"`
	SignatureName  string    `json:"signature_name"`
	FooterText     string    `json:"footer_text"`
}

func (q *Queries) UpdateCertificateTemplate(ctx context.Context, arg UpdateCertificateTemplateParams) (CertificateTemplate, error) {
	row := q.db.QueryRow(ctx, updateCertificateTemplate,
		arg.ID,
		arg.Name,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.LogoUrl,
		arg.Title,
		arg.Subtitle,
		arg.BodyText,
		arg.IssuerName,
		arg.SignatureName,
		arg.FooterText,
	)
	var i CertificateTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.LogoUrl,
		&i.Title,
		&i.Subtitle,
		&i.BodyText,
		&i.IssuerName,
		&i.SignatureName,
		&i.FooterText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
