// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByPostIDs = `-- name: CountCommentsByPostIDs :many
select post_id, count(*) as comment_count
from comments
where post_id = any($1::uuid[]) and deleted_at is null
group by post_id
`

type CountCommentsByPostIDsRow struct {
	PostID       uuid.UUID `json:"post_id"`
	CommentCount int64     `json:"comment_count"`
}

func (q *Queries) CountCommentsByPostIDs(ctx context.Context, postIds []uuid.UUID) ([]CountCommentsByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, countCommentsByPostIDs, postIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCommentsByPostIDsRow
	for rows.Next() {
		var i CountCommentsByPostIDsRow
		if err := rows.Scan(&i.PostID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createComment = `-- name: CreateComment :one
insert into comments (post_id, parent_comment_id, author_id, content)
values ($1, $2, $3, $4)
returning id, post_id, parent_comment_id, author_id, content, created_at, edited_at, deleted_at
`

type CreateCommentParams struct {
	PostID          uuid.UUID   `json:"post_id"`
	ParentCommentID pgtype.UUID `json:"parent_comment_id"`
	AuthorID        uuid.UUID   `json:"author_id"`
	Content         string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.ParentCommentID,
		arg.AuthorID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentCommentID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentAuthorID = `-- name: GetCommentAuthorID :one
select author_id from comments where id = $1 and deleted_at is null
`

func (q *Queries) GetCommentAuthorID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCommentAuthorID, id)
	var author_id uuid.UUID
	err := row.Scan(&author_id)
	return author_id, err
}

const getCommentByID = `-- name: GetCommentByID :one
select id, post_id, parent_comment_id, author_id, content, created_at, edited_at, deleted_at from comments where id = $1 and deleted_at is null
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentCommentID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCommentsByPostID = `-- name: ListCommentsByPostID :many
select
  c.id, c.post_id, c.parent_comment_id, c.author_id, c.content, c.created_at, c.edited_at, c.deleted_at,
  u.email as author_email,
  pr.member_id as author_member_id,
  pr.display_name as author_display_name
from comments c
join users u on u.id = c.author_id
join profiles pr on pr.user_id = c.author_id
where c.post_id = $1 and c.deleted_at is null
order by c.created_at asc
`

type ListCommentsByPostIDRow struct {
	ID                uuid.UUID          `json:"id"`
	PostID            uuid.UUID          `json:"post_id"`
	ParentCommentID   pgtype.UUID        `json:"parent_comment_id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	Content           string             `json:"content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	AuthorEmail       string             `json:"author_email"`
	AuthorMemberID    string             `json:"author_member_id"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
}

// Flat list, semua comment (top-level + reply) untuk satu post. Client
// bina tree guna parent_comment_id.
func (q *Queries) ListCommentsByPostID(ctx context.Context, postID uuid.UUID) ([]ListCommentsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByPostIDRow
	for rows.Next() {
		var i ListCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentCommentID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.AuthorEmail,
			&i.AuthorMemberID,
			&i.AuthorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
update comments set deleted_at = now() where id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const updateComment = `-- name: UpdateComment :one
update comments
set content = $2, edited_at = now()
where id = $1 and deleted_at is null
returning id, post_id, parent_comment_id, author_id, content, created_at, edited_at, deleted_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentCommentID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}
