// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activityStatsThisMonth = `-- name: ActivityStatsThisMonth :one
select
  (select count(*) from activities
    where deleted_at is null and status = 'published' and ends_at >= now())
    as upcoming,
  (select count(*) from activity_registrations
    where status <> 'cancelled' and registered_at >= date_trunc('month', now()))
    as registrations_this_month,
  (select case when denom.jumlah = 0 then null
               else numer.jumlah::float8 / denom.jumlah::float8 end
   from
     (select count(*) as jumlah from activity_attendances at
       join activity_sessions s on s.id = at.session_id
      where s.ends_at >= date_trunc('month', now()) and s.ends_at < now()) numer,
     (select count(*) as jumlah from activity_registrations r
       where r.status <> 'cancelled'
         and r.activity_id in (
           select s.activity_id from activity_sessions s
            where s.ends_at >= date_trunc('month', now()) and s.ends_at < now())) denom
  ) as attendance_rate
`

type ActivityStatsThisMonthRow struct {
	Upcoming               int64       `json:"upcoming"`
	RegistrationsThisMonth int64       `json:"registrations_this_month"`
	AttendanceRate         interface{} `json:"attendance_rate"`
}

// attendance_rate: kehadiran direkod bagi sesi yang SUDAH TAMAT dalam
// bulan semasa, dibahagi pendaftaran aktif pada aktiviti sesi-sesi itu.
// Sesi belum tamat dikecualikan supaya kadar tidak nampak rendah palsu
// sepanjang bulan berjalan. Pembahagi sifar -> null (bukan 0).
func (q *Queries) ActivityStatsThisMonth(ctx context.Context) (ActivityStatsThisMonthRow, error) {
	row := q.db.QueryRow(ctx, activityStatsThisMonth)
	var i ActivityStatsThisMonthRow
	err := row.Scan(&i.Upcoming, &i.RegistrationsThisMonth, &i.AttendanceRate)
	return i, err
}

const countApprovedMembers = `-- name: CountApprovedMembers :one
select count(*) from profiles
where status = 'approved' and is_active = true
`

func (q *Queries) CountApprovedMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMyCertificates = `-- name: CountMyCertificates :one
select count(*) from activity_certificates
where user_id = $1 and revoked_at is null
`

func (q *Queries) CountMyCertificates(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMyCertificates, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewMembersThisMonth = `-- name: CountNewMembersThisMonth :one
select count(*) from profiles
where approved_at >= date_trunc('month', now())
`

func (q *Queries) CountNewMembersThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNewMembersThisMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingMembers = `-- name: CountPendingMembers :one
select count(*) from profiles where status = 'pending'
`

func (q *Queries) CountPendingMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
select count(*) from notifications
where recipient_id = $1 and read_at is null
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMyUpcomingRegistrations = `-- name: ListMyUpcomingRegistrations :many
select r.id, r.activity_id, r.payment_status,
  a.title, a.starts_at, a.ends_at, c.name as category_name
from activity_registrations r
join activities a on a.id = r.activity_id
join activity_categories c on c.id = a.category_id
where r.user_id = $1
  and r.status <> 'cancelled'
  and a.deleted_at is null
  and a.ends_at >= now()
order by a.starts_at asc
limit 3
`

type ListMyUpcomingRegistrationsRow struct {
	ID            uuid.UUID          `json:"id"`
	ActivityID    uuid.UUID          `json:"activity_id"`
	PaymentStatus string             `json:"payment_status"`
	Title         string             `json:"title"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	CategoryName  string             `json:"category_name"`
}

// Corak ListMyRegistrations (activity_registrations.sql:206) tetapi
// hanya yang BELUM tamat dan dihadkan 3 - kad dashboard, bukan senarai
// penuh (itu /my-activities).
func (q *Queries) ListMyUpcomingRegistrations(ctx context.Context, userID uuid.UUID) ([]ListMyUpcomingRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listMyUpcomingRegistrations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyUpcomingRegistrationsRow
	for rows.Next() {
		var i ListMyUpcomingRegistrationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.PaymentStatus,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenActivitiesForMe = `-- name: ListOpenActivitiesForMe :many
select a.id, a.title, a.starts_at, a.fee_cents, a.currency,
  c.name as category_name,
  (select count(*) from activity_registrations r2
    where r2.activity_id = a.id and r2.status <> 'cancelled') as registration_count
from activities a
join activity_categories c on c.id = a.category_id
where a.deleted_at is null
  and a.status = 'published'
  and a.ends_at >= now()
  and not exists (
    select 1 from activity_registrations r
    where r.activity_id = a.id and r.user_id = $1 and r.status <> 'cancelled'
  )
order by a.starts_at asc
limit 3
`

type ListOpenActivitiesForMeRow struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	FeeCents          int32              `json:"fee_cents"`
	Currency          string             `json:"currency"`
	CategoryName      string             `json:"category_name"`
	RegistrationCount int64              `json:"registration_count"`
}

// Aktiviti terbitan akan datang yang pemanggil BELUM daftar. `not
// exists` (bukan left join + is null) supaya perancang boleh berhenti
// pada padanan pertama.
func (q *Queries) ListOpenActivitiesForMe(ctx context.Context, userID uuid.UUID) ([]ListOpenActivitiesForMeRow, error) {
	rows, err := q.db.Query(ctx, listOpenActivitiesForMe, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenActivitiesForMeRow
	for rows.Next() {
		var i ListOpenActivitiesForMeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartsAt,
			&i.FeeCents,
			&i.Currency,
			&i.CategoryName,
			&i.RegistrationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberStatsByDepartment = `-- name: MemberStatsByDepartment :many
select coalesce(d.code, '') as code,
       coalesce(d.name, 'Tiada bahagian') as name,
       count(*) as count
from profiles p
left join departments d on d.code = p.department_code
where p.status = 'approved' and p.is_active = true
group by d.code, d.name
order by count desc
`

type MemberStatsByDepartmentRow struct {
	Code  string `json:"code"`
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

// Tanpa had di sini - handler yang memotong kepada 6 teratas + baris
// "Lain-lain", supaya jumlah keseluruhan kekal tepat.
func (q *Queries) MemberStatsByDepartment(ctx context.Context) ([]MemberStatsByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, memberStatsByDepartment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberStatsByDepartmentRow
	for rows.Next() {
		var i MemberStatsByDepartmentRow
		if err := rows.Scan(&i.Code, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumActivityRevenueThisMonth = `-- name: SumActivityRevenueThisMonth :one
select coalesce(sum(fee_cents_paid), 0)::bigint
from activity_registrations
where payment_status = 'paid'
  and fee_cents_paid is not null
  and registered_at >= date_trunc('month', now())
`

// fee_cents_paid = snapshot amaun yang BENAR-BENAR dibayar; sengaja
// BUKAN activities.fee_cents hidup (yuran boleh ditukar selepas bayar).
func (q *Queries) SumActivityRevenueThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumActivityRevenueThisMonth)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumDonationRevenueThisMonth = `-- name: SumDonationRevenueThisMonth :one
select coalesce(sum(amount_cents), 0)::bigint
from donations
where status = 'succeeded' and created_at >= date_trunc('month', now())
`

func (q *Queries) SumDonationRevenueThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumDonationRevenueThisMonth)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumRegistrationRevenueThisMonth = `-- name: SumRegistrationRevenueThisMonth :one
select coalesce(sum(amount_cents), 0)::bigint
from registration_payments
where status = 'succeeded' and created_at >= date_trunc('month', now())
`

func (q *Queries) SumRegistrationRevenueThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumRegistrationRevenueThisMonth)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
