// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDepartment = `-- name: AddDepartment :one
insert into departments (code, name, sort_order, added_by)
values ($1, $2, $3, $4)
returning code, name, sort_order, added_by, created_at
`

type AddDepartmentParams struct {
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	AddedBy   pgtype.UUID `json:"added_by"`
}

func (q *Queries) AddDepartment(ctx context.Context, arg AddDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, addDepartment,
		arg.Code,
		arg.Name,
		arg.SortOrder,
		arg.AddedBy,
	)
	var i Department
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const departmentExists = `-- name: DepartmentExists :one
select exists(select 1 from departments where code = $1)
`

func (q *Queries) DepartmentExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, departmentExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDepartments = `-- name: ListDepartments :many
select code, name, sort_order, added_by, created_at from departments order by sort_order asc, name asc
`

// Skrin pengurusan CRUD bahagian/jabatan - susunan organisasi (bukan abjad).
func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.AddedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDepartment = `-- name: RemoveDepartment :execrows
delete from departments where code = $1
`

func (q *Queries) RemoveDepartment(ctx context.Context, code string) (int64, error) {
	result, err := q.db.Exec(ctx, removeDepartment, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDepartment = `-- name: UpdateDepartment :one
update departments
set
  name = coalesce($1::text, name),
  sort_order = coalesce($2::int, sort_order)
where code = $3
returning code, name, sort_order, added_by, created_at
`

type UpdateDepartmentParams struct {
	Name      pgtype.Text `json:"name"`
	SortOrder pgtype.Int4 `json:"sort_order"`
	Code      string      `json:"code"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment, arg.Name, arg.SortOrder, arg.Code)
	var i Department
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}
