// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
delete from device_tokens where id = $1 and user_id = $2
`

type DeleteDeviceTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.ID, arg.UserID)
	return err
}

const deleteDeviceTokenByOnesignalID = `-- name: DeleteDeviceTokenByOnesignalID :exec
delete from device_tokens where onesignal_id = $1 and user_id = $2
`

type DeleteDeviceTokenByOnesignalIDParams struct {
	OnesignalID string    `json:"onesignal_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeviceTokenByOnesignalID(ctx context.Context, arg DeleteDeviceTokenByOnesignalIDParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokenByOnesignalID, arg.OnesignalID, arg.UserID)
	return err
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
select id, user_id, onesignal_id, platform, created_at, updated_at from device_tokens where user_id = $1
`

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OnesignalID,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
insert into device_tokens (user_id, onesignal_id, platform, updated_at)
values ($1, $2, $3, now())
on conflict (onesignal_id) do update set
  user_id = excluded.user_id,
  platform = excluded.platform,
  updated_at = now()
`

type UpsertDeviceTokenParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	OnesignalID string      `json:"onesignal_id"`
	Platform    pgtype.Text `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken, arg.UserID, arg.OnesignalID, arg.Platform)
	return err
}
