// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: donations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDonation = `-- name: CreateDonation :one
insert into donations (user_id, donor_name, donor_email, amount_cents, currency, gateway, gateway_ref, status)
values ($1, $2, $3, $4, $5, $6, $7, 'pending')
returning id, user_id, donor_name, donor_email, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type CreateDonationParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DonorName   pgtype.Text `json:"donor_name"`
	DonorEmail  pgtype.Text `json:"donor_email"`
	AmountCents int32       `json:"amount_cents"`
	Currency    string      `json:"currency"`
	Gateway     string      `json:"gateway"`
	GatewayRef  string      `json:"gateway_ref"`
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRow(ctx, createDonation,
		arg.UserID,
		arg.DonorName,
		arg.DonorEmail,
		arg.AmountCents,
		arg.Currency,
		arg.Gateway,
		arg.GatewayRef,
	)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DonorName,
		&i.DonorEmail,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getDonationByGatewayRef = `-- name: GetDonationByGatewayRef :one
select id, user_id, donor_name, donor_email, amount_cents, currency, gateway, gateway_ref, status, created_at from donations where gateway = $1 and gateway_ref = $2
`

type GetDonationByGatewayRefParams struct {
	Gateway    string `json:"gateway"`
	GatewayRef string `json:"gateway_ref"`
}

func (q *Queries) GetDonationByGatewayRef(ctx context.Context, arg GetDonationByGatewayRefParams) (Donation, error) {
	row := q.db.QueryRow(ctx, getDonationByGatewayRef, arg.Gateway, arg.GatewayRef)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DonorName,
		&i.DonorEmail,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMyDonationByID = `-- name: GetMyDonationByID :one
select id, user_id, donor_name, donor_email, amount_cents, currency, gateway, gateway_ref, status, created_at from donations where id = $1 and user_id = $2
`

type GetMyDonationByIDParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Resit — hanya donation SENDIRI (ahli log masuk, user_id = caller).
// Donation anonymous (user_id null) TIADA laluan muat turun resit sini —
// emel resit yang dihantar semasa webhook satu-satunya jejak mereka ada,
// tiada akaun untuk log masuk dan tuntut baris ni.
func (q *Queries) GetMyDonationByID(ctx context.Context, arg GetMyDonationByIDParams) (Donation, error) {
	row := q.db.QueryRow(ctx, getMyDonationByID, arg.ID, arg.UserID)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DonorName,
		&i.DonorEmail,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listMyDonations = `-- name: ListMyDonations :many
select id, user_id, donor_name, donor_email, amount_cents, currency, gateway, gateway_ref, status, created_at from donations
where user_id = $1
order by created_at desc
`

// Sejarah derma seorang ahli, untuk `GET /me/payments` (L33, 2026-08-22).
//
// Tanpa query ni, `GET /me/payments/donation/:id/receipt` mati secara
// praktikal: ia perlukan `donations.id`, dan tiada permukaan API yang
// pernah mendedahkan id itu kepada pemiliknya. Endpoint resit wujud sejak
// awal; yang hilang cuma cara menemuinya.
//
// Diskop `user_id`, jadi derma TANPA NAMA (user_id null) tak pernah
// muncul — betul: penderma itu tiada akaun untuk menuntut baris ni, dan
// emel resit yang dihantar semasa webhook ialah satu-satunya jejak mereka
// ada, mengikut reka bentuk (lihat komen `GetMyDonationByID`).
//
// Status 'pending'/'failed' TURUT dipulangkan (bukan 'succeeded' sahaja),
// padanan `ListMyRegistrationPayments`: sejarah patut menunjukkan
// percubaan yang gagal, bukan senyap menghilangkannya. Butang resit
// digate pada status di sisi klien.
func (q *Queries) ListMyDonations(ctx context.Context, userID pgtype.UUID) ([]Donation, error) {
	rows, err := q.db.Query(ctx, listMyDonations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Donation
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DonorName,
			&i.DonorEmail,
			&i.AmountCents,
			&i.Currency,
			&i.Gateway,
			&i.GatewayRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDonationsOlderThan = `-- name: ListPendingDonationsOlderThan :many
select id, user_id, donor_name, donor_email, amount_cents, currency, gateway, gateway_ref, status, created_at from donations
where status = 'pending'
  and created_at < $1
  and created_at > $2
order by created_at
limit $3
`

type ListPendingDonationsOlderThanParams struct {
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	Oldest      pgtype.Timestamptz `json:"oldest"`
	RowLimit    int32              `json:"row_limit"`
}

// Baris 'pending' yang dah cukup umur untuk layak disemak semula terus
// pada gateway (internal/paymentreconcile) — padanan alasan
// ListPendingRegistrationPaymentsOlderThan (registration_payments.sql):
// cuma 'pending', bukan 'failed' (terminal, tak perlu disemak semula).
//
// Tingkap atas + limit — lihat komen penuh pada
// `ListPendingRegistrationPaymentsOlderThan` (L30). Sebab sama terpakai:
// PaymentIntent Stripe yang ditinggalkan kekal `requires_payment_method`,
// yang `CheckStatus` petakan kepada "pending" selama-lamanya.
func (q *Queries) ListPendingDonationsOlderThan(ctx context.Context, arg ListPendingDonationsOlderThanParams) ([]Donation, error) {
	rows, err := q.db.Query(ctx, listPendingDonationsOlderThan, arg.StaleBefore, arg.Oldest, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Donation
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DonorName,
			&i.DonorEmail,
			&i.AmountCents,
			&i.Currency,
			&i.Gateway,
			&i.GatewayRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDonationStatusByGatewayRef = `-- name: UpdateDonationStatusByGatewayRef :one
update donations
set status = $3
where gateway = $1 and gateway_ref = $2 and status <> 'succeeded'
returning id, user_id, donor_name, donor_email, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type UpdateDonationStatusByGatewayRefParams struct {
	Gateway    string `json:"gateway"`
	GatewayRef string `json:"gateway_ref"`
	Status     string `json:"status"`
}

// `status <> 'succeeded'` = 'succeeded' ialah keadaan TERMINAL: webhook
// retry/replay (atau event lewat sampai tak ikut turutan) tak boleh
// turunkan donation yang dah berjaya jadi 'failed'. Kad yang ditolak
// kemudian dicuba semula atas PaymentIntent yang sama tetap boleh naik
// 'failed' -> 'succeeded' (sebab itu bukan `status = 'pending'`).
func (q *Queries) UpdateDonationStatusByGatewayRef(ctx context.Context, arg UpdateDonationStatusByGatewayRefParams) (Donation, error) {
	row := q.db.QueryRow(ctx, updateDonationStatusByGatewayRef, arg.Gateway, arg.GatewayRef, arg.Status)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DonorName,
		&i.DonorEmail,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
