// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailVerificationSendsSince = `-- name: CountEmailVerificationSendsSince :one
select count(*)::int from email_verification_sends
where user_id = $1 and created_at > $2
`

type CountEmailVerificationSendsSinceParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountEmailVerificationSendsSince(ctx context.Context, arg CountEmailVerificationSendsSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countEmailVerificationSendsSince, arg.UserID, arg.CreatedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
insert into email_verification_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, user_id, token_hash, expires_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
delete from email_verification_tokens where id = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, id)
	return err
}

const deleteEmailVerificationTokensByUser = `-- name: DeleteEmailVerificationTokensByUser :exec
delete from email_verification_tokens where user_id = $1
`

func (q *Queries) DeleteEmailVerificationTokensByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensByUser, userID)
	return err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
select id, user_id, token_hash, expires_at, created_at from email_verification_tokens where token_hash = $1
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestEmailVerificationSendAt = `-- name: GetLatestEmailVerificationSendAt :one
select created_at from email_verification_sends
where user_id = $1
order by created_at desc
limit 1
`

func (q *Queries) GetLatestEmailVerificationSendAt(ctx context.Context, userID uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestEmailVerificationSendAt, userID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertEmailVerificationSend = `-- name: InsertEmailVerificationSend :exec
insert into email_verification_sends (user_id) values ($1)
`

func (q *Queries) InsertEmailVerificationSend(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertEmailVerificationSend, userID)
	return err
}
