// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
insert into email_verification_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, user_id, token_hash, expires_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
delete from email_verification_tokens where id = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, id)
	return err
}

const deleteEmailVerificationTokensByUser = `-- name: DeleteEmailVerificationTokensByUser :exec
delete from email_verification_tokens where user_id = $1
`

func (q *Queries) DeleteEmailVerificationTokensByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensByUser, userID)
	return err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
select id, user_id, token_hash, expires_at, created_at from email_verification_tokens where token_hash = $1
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
