// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const commentsLikedByUser = `-- name: CommentsLikedByUser :many
select comment_id from comment_likes
where user_id = $1 and comment_id = any($2::uuid[])
`

type CommentsLikedByUserParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	CommentIds []uuid.UUID `json:"comment_ids"`
}

func (q *Queries) CommentsLikedByUser(ctx context.Context, arg CommentsLikedByUserParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, commentsLikedByUser, arg.UserID, arg.CommentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var comment_id uuid.UUID
		if err := rows.Scan(&comment_id); err != nil {
			return nil, err
		}
		items = append(items, comment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCommentLikesByCommentIDs = `-- name: CountCommentLikesByCommentIDs :many
select comment_id, count(*) as like_count
from comment_likes
where comment_id = any($1::uuid[])
group by comment_id
`

type CountCommentLikesByCommentIDsRow struct {
	CommentID uuid.UUID `json:"comment_id"`
	LikeCount int64     `json:"like_count"`
}

func (q *Queries) CountCommentLikesByCommentIDs(ctx context.Context, commentIds []uuid.UUID) ([]CountCommentLikesByCommentIDsRow, error) {
	rows, err := q.db.Query(ctx, countCommentLikesByCommentIDs, commentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCommentLikesByCommentIDsRow
	for rows.Next() {
		var i CountCommentLikesByCommentIDsRow
		if err := rows.Scan(&i.CommentID, &i.LikeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPostLikes = `-- name: CountPostLikes :one
select count(*) from post_likes where post_id = $1
`

func (q *Queries) CountPostLikes(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPostLikes, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostLikesByPostIDs = `-- name: CountPostLikesByPostIDs :many
select post_id, count(*) as like_count
from post_likes
where post_id = any($1::uuid[])
group by post_id
`

type CountPostLikesByPostIDsRow struct {
	PostID    uuid.UUID `json:"post_id"`
	LikeCount int64     `json:"like_count"`
}

func (q *Queries) CountPostLikesByPostIDs(ctx context.Context, postIds []uuid.UUID) ([]CountPostLikesByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, countPostLikesByPostIDs, postIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPostLikesByPostIDsRow
	for rows.Next() {
		var i CountPostLikesByPostIDsRow
		if err := rows.Scan(&i.PostID, &i.LikeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likeComment = `-- name: LikeComment :exec
insert into comment_likes (comment_id, user_id)
values ($1, $2)
on conflict (comment_id, user_id) do nothing
`

type LikeCommentParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) LikeComment(ctx context.Context, arg LikeCommentParams) error {
	_, err := q.db.Exec(ctx, likeComment, arg.CommentID, arg.UserID)
	return err
}

const likePost = `-- name: LikePost :execrows
insert into post_likes (post_id, user_id)
values ($1, $2)
on conflict (post_id, user_id) do nothing
`

type LikePostParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, likePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const postLikedByUser = `-- name: PostLikedByUser :one
select exists(select 1 from post_likes where post_id = $1 and user_id = $2)
`

type PostLikedByUserParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) PostLikedByUser(ctx context.Context, arg PostLikedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, postLikedByUser, arg.PostID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const postsLikedByUser = `-- name: PostsLikedByUser :many
select post_id from post_likes
where user_id = $1 and post_id = any($2::uuid[])
`

type PostsLikedByUserParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	PostIds []uuid.UUID `json:"post_ids"`
}

// Untuk tandakan "liked_by_me" bila list post — pulang subset post_ids
// yang user ni dah like.
func (q *Queries) PostsLikedByUser(ctx context.Context, arg PostsLikedByUserParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, postsLikedByUser, arg.UserID, arg.PostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var post_id uuid.UUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlikeComment = `-- name: UnlikeComment :exec
delete from comment_likes where comment_id = $1 and user_id = $2
`

type UnlikeCommentParams struct {
	CommentID uuid.UUID `json:"comment_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error {
	_, err := q.db.Exec(ctx, unlikeComment, arg.CommentID, arg.UserID)
	return err
}

const unlikePost = `-- name: UnlikePost :exec
delete from post_likes where post_id = $1 and user_id = $2
`

type UnlikePostParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.Exec(ctx, unlikePost, arg.PostID, arg.UserID)
	return err
}
