// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member_addresses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAddressesByUser = `-- name: CountAddressesByUser :one
select count(*) from member_addresses where user_id = $1
`

// Had 3 alamat/ahli disemak app-layer (bukan constraint DB, "3" ialah
// peraturan produk boleh berubah) — dipanggil dalam transaksi yang sama
// sebelum INSERT, padanan cara sequences/nombor ahli dikira.
func (q *Queries) CountAddressesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :one
insert into member_addresses (
  user_id, label, is_default, address_type, unit_number, floor, block,
  street, township, city, postcode, state
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
returning id, user_id, label, is_default, address_type, unit_number, floor, block, street, township, city, postcode, state, created_at, updated_at
`

type CreateAddressParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Label       pgtype.Text `json:"label"`
	IsDefault   bool        `json:"is_default"`
	AddressType string      `json:"address_type"`
	UnitNumber  pgtype.Text `json:"unit_number"`
	Floor       pgtype.Text `json:"floor"`
	Block       pgtype.Text `json:"block"`
	Street      pgtype.Text `json:"street"`
	Township    pgtype.Text `json:"township"`
	City        string      `json:"city"`
	Postcode    string      `json:"postcode"`
	State       string      `json:"state"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (MemberAddress, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.IsDefault,
		arg.AddressType,
		arg.UnitNumber,
		arg.Floor,
		arg.Block,
		arg.Street,
		arg.Township,
		arg.City,
		arg.Postcode,
		arg.State,
	)
	var i MemberAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.IsDefault,
		&i.AddressType,
		&i.UnitNumber,
		&i.Floor,
		&i.Block,
		&i.Street,
		&i.Township,
		&i.City,
		&i.Postcode,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
delete from member_addresses where id = $1 and user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	return err
}

const getAddressByIDAndUser = `-- name: GetAddressByIDAndUser :one
select id, user_id, label, is_default, address_type, unit_number, floor, block, street, township, city, postcode, state, created_at, updated_at from member_addresses
where id = $1 and user_id = $2
`

type GetAddressByIDAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Ownership dikuatkuasakan DALAM query (bukan cuma filter selepas fetch)
// — padanan corak `authz` package: query yang tak filter guna user id
// dari token bermakna ownership tak dikuatkuasakan.
func (q *Queries) GetAddressByIDAndUser(ctx context.Context, arg GetAddressByIDAndUserParams) (MemberAddress, error) {
	row := q.db.QueryRow(ctx, getAddressByIDAndUser, arg.ID, arg.UserID)
	var i MemberAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.IsDefault,
		&i.AddressType,
		&i.UnitNumber,
		&i.Floor,
		&i.Block,
		&i.Street,
		&i.Township,
		&i.City,
		&i.Postcode,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOldestOtherByUser = `-- name: GetOldestOtherByUser :one
select id, user_id, label, is_default, address_type, unit_number, floor, block, street, township, city, postcode, state, created_at, updated_at from member_addresses
where user_id = $1 and id <> $2
order by created_at asc
limit 1
`

type GetOldestOtherByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

// Auto-promote lepas default dipadam — baris PALING LAMA (created_at)
// selain baris yang baru dipadam jadi default baharu.
func (q *Queries) GetOldestOtherByUser(ctx context.Context, arg GetOldestOtherByUserParams) (MemberAddress, error) {
	row := q.db.QueryRow(ctx, getOldestOtherByUser, arg.UserID, arg.ID)
	var i MemberAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.IsDefault,
		&i.AddressType,
		&i.UnitNumber,
		&i.Floor,
		&i.Block,
		&i.Street,
		&i.Township,
		&i.City,
		&i.Postcode,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
select id, user_id, label, is_default, address_type, unit_number, floor, block, street, township, city, postcode, state, created_at, updated_at from member_addresses
where user_id = $1
order by is_default desc, created_at asc
`

func (q *Queries) ListAddressesByUser(ctx context.Context, userID uuid.UUID) ([]MemberAddress, error) {
	rows, err := q.db.Query(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberAddress
	for rows.Next() {
		var i MemberAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.IsDefault,
			&i.AddressType,
			&i.UnitNumber,
			&i.Floor,
			&i.Block,
			&i.Street,
			&i.Township,
			&i.City,
			&i.Postcode,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefault = `-- name: SetDefault :one
update member_addresses set is_default = true, updated_at = now()
where id = $1 and user_id = $2
returning id, user_id, label, is_default, address_type, unit_number, floor, block, street, township, city, postcode, state, created_at, updated_at
`

type SetDefaultParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SetDefault(ctx context.Context, arg SetDefaultParams) (MemberAddress, error) {
	row := q.db.QueryRow(ctx, setDefault, arg.ID, arg.UserID)
	var i MemberAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.IsDefault,
		&i.AddressType,
		&i.UnitNumber,
		&i.Floor,
		&i.Block,
		&i.Street,
		&i.Township,
		&i.City,
		&i.Postcode,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unsetDefaultForUser = `-- name: UnsetDefaultForUser :exec
update member_addresses set is_default = false, updated_at = now()
where user_id = $1 and is_default
`

// Nyahtetapkan default LAMA sebelum tetapkan default BAHARU, dalam
// transaksi yang sama — partial unique index (satu default/ahli) akan
// tolak dua baris `is_default=true` serentak kalau susunan ni songsang.
func (q *Queries) UnsetDefaultForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsetDefaultForUser, userID)
	return err
}

const updateAddress = `-- name: UpdateAddress :one
update member_addresses
set
  label = coalesce($1::text, label),
  address_type = coalesce($2::text, address_type),
  unit_number = coalesce($3::text, unit_number),
  floor = coalesce($4::text, floor),
  block = coalesce($5::text, block),
  street = coalesce($6::text, street),
  township = coalesce($7::text, township),
  city = coalesce($8::text, city),
  postcode = coalesce($9::text, postcode),
  state = coalesce($10::text, state),
  updated_at = now()
where id = $11 and user_id = $12
returning id, user_id, label, is_default, address_type, unit_number, floor, block, street, township, city, postcode, state, created_at, updated_at
`

type UpdateAddressParams struct {
	Label       pgtype.Text `json:"label"`
	AddressType pgtype.Text `json:"address_type"`
	UnitNumber  pgtype.Text `json:"unit_number"`
	Floor       pgtype.Text `json:"floor"`
	Block       pgtype.Text `json:"block"`
	Street      pgtype.Text `json:"street"`
	Township    pgtype.Text `json:"township"`
	City        pgtype.Text `json:"city"`
	Postcode    pgtype.Text `json:"postcode"`
	State       pgtype.Text `json:"state"`
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
}

// Partial update — medan tak dihantar (narg NULL) kekal nilai asal,
// padanan pola UpdateProfile. `is_default` sengaja TIDAK di sini —
// ditetapkan berasingan (SetDefault) dalam transaksi yang turut
// nyahtetapkan default lama, supaya invariant "paling banyak SATU
// default" sentiasa dikekalkan sepanjang transaksi.
func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (MemberAddress, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.Label,
		arg.AddressType,
		arg.UnitNumber,
		arg.Floor,
		arg.Block,
		arg.Street,
		arg.Township,
		arg.City,
		arg.Postcode,
		arg.State,
		arg.ID,
		arg.UserID,
	)
	var i MemberAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.IsDefault,
		&i.AddressType,
		&i.UnitNumber,
		&i.Floor,
		&i.Block,
		&i.Street,
		&i.Township,
		&i.City,
		&i.Postcode,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
