// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member_bans.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const banProfile = `-- name: BanProfile :one
update profiles
set banned_at = now(),
    ban_expires_at = $4::timestamptz,
    ban_reason = $2,
    banned_by = $3,
    updated_at = now()
where user_id = $1
  and banned_at is null
returning id, user_id, member_id, display_name, phone, role_id, email_verified, created_at, status, approved_by, approved_at, avatar_r2_key, telegram_chat_id, telegram_username, telegram_linked_at, emergency_contact_name, emergency_contact_phone, health_notes, is_active, department_code, position, staff_id, staff_id_verified_at, staff_id_verified_by, updated_at, banned_at, ban_expires_at, ban_reason, banned_by
`

type BanProfileParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	BanReason    pgtype.Text        `json:"ban_reason"`
	BannedBy     pgtype.UUID        `json:"banned_by"`
	BanExpiresAt pgtype.Timestamptz `json:"ban_expires_at"`
}

func (q *Queries) BanProfile(ctx context.Context, arg BanProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, banProfile,
		arg.UserID,
		arg.BanReason,
		arg.BannedBy,
		arg.BanExpiresAt,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MemberID,
		&i.DisplayName,
		&i.Phone,
		&i.RoleID,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AvatarR2Key,
		&i.TelegramChatID,
		&i.TelegramUsername,
		&i.TelegramLinkedAt,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.HealthNotes,
		&i.IsActive,
		&i.DepartmentCode,
		&i.Position,
		&i.StaffID,
		&i.StaffIDVerifiedAt,
		&i.StaffIDVerifiedBy,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.BanExpiresAt,
		&i.BanReason,
		&i.BannedBy,
	)
	return i, err
}

const isUserCurrentlyBanned = `-- name: IsUserCurrentlyBanned :one
select exists (
  select 1
  from profiles
  where user_id = $1
    and banned_at is not null
    and (ban_expires_at is null or ban_expires_at > now())
)
`

func (q *Queries) IsUserCurrentlyBanned(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserCurrentlyBanned, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBannedProfiles = `-- name: ListBannedProfiles :many
select
  p.user_id,
  p.member_id,
  p.display_name,
  u.email,
  r.key as role_key,
  p.banned_at,
  p.ban_expires_at,
  p.ban_reason,
  p.banned_by
from profiles p
join users u on u.id = p.user_id
join roles r on r.id = p.role_id
where p.banned_at is not null
  and (p.ban_expires_at is null or p.ban_expires_at > now())
order by p.ban_expires_at nulls first, p.banned_at desc
`

type ListBannedProfilesRow struct {
	UserID       uuid.UUID          `json:"user_id"`
	MemberID     pgtype.Text        `json:"member_id"`
	DisplayName  pgtype.Text        `json:"display_name"`
	Email        string             `json:"email"`
	RoleKey      string             `json:"role_key"`
	BannedAt     pgtype.Timestamptz `json:"banned_at"`
	BanExpiresAt pgtype.Timestamptz `json:"ban_expires_at"`
	BanReason    pgtype.Text        `json:"ban_reason"`
	BannedBy     pgtype.UUID        `json:"banned_by"`
}

func (q *Queries) ListBannedProfiles(ctx context.Context) ([]ListBannedProfilesRow, error) {
	rows, err := q.db.Query(ctx, listBannedProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBannedProfilesRow
	for rows.Next() {
		var i ListBannedProfilesRow
		if err := rows.Scan(
			&i.UserID,
			&i.MemberID,
			&i.DisplayName,
			&i.Email,
			&i.RoleKey,
			&i.BannedAt,
			&i.BanExpiresAt,
			&i.BanReason,
			&i.BannedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanProfile = `-- name: UnbanProfile :one
update profiles
set banned_at = null,
    ban_expires_at = null,
    ban_reason = null,
    banned_by = null,
    updated_at = now()
where user_id = $1
  and banned_at is not null
returning id, user_id, member_id, display_name, phone, role_id, email_verified, created_at, status, approved_by, approved_at, avatar_r2_key, telegram_chat_id, telegram_username, telegram_linked_at, emergency_contact_name, emergency_contact_phone, health_notes, is_active, department_code, position, staff_id, staff_id_verified_at, staff_id_verified_by, updated_at, banned_at, ban_expires_at, ban_reason, banned_by
`

func (q *Queries) UnbanProfile(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, unbanProfile, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MemberID,
		&i.DisplayName,
		&i.Phone,
		&i.RoleID,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AvatarR2Key,
		&i.TelegramChatID,
		&i.TelegramUsername,
		&i.TelegramLinkedAt,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.HealthNotes,
		&i.IsActive,
		&i.DepartmentCode,
		&i.Position,
		&i.StaffID,
		&i.StaffIDVerifiedAt,
		&i.StaffIDVerifiedBy,
		&i.UpdatedAt,
		&i.BannedAt,
		&i.BanExpiresAt,
		&i.BanReason,
		&i.BannedBy,
	)
	return i, err
}
