// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID              uuid.UUID          `json:"id"`
	PostID          uuid.UUID          `json:"post_id"`
	ParentCommentID pgtype.UUID        `json:"parent_comment_id"`
	AuthorID        uuid.UUID          `json:"author_id"`
	Content         string             `json:"content"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type CommentLike struct {
	CommentID uuid.UUID          `json:"comment_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DeviceToken struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	OnesignalID string             `json:"onesignal_id"`
	Platform    pgtype.Text        `json:"platform"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Donation struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	DonorName   pgtype.Text        `json:"donor_name"`
	DonorEmail  pgtype.Text        `json:"donor_email"`
	AmountCents int32              `json:"amount_cents"`
	Currency    string             `json:"currency"`
	Gateway     string             `json:"gateway"`
	GatewayRef  string             `json:"gateway_ref"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EmailVerificationToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID          uuid.UUID          `json:"id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	ActorID     uuid.UUID          `json:"actor_id"`
	Type        string             `json:"type"`
	PostID      pgtype.UUID        `json:"post_id"`
	CommentID   pgtype.UUID        `json:"comment_id"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PendingUpload struct {
	R2Key     string             `json:"r2_key"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID        uuid.UUID          `json:"id"`
	AuthorID  uuid.UUID          `json:"author_id"`
	Type      string             `json:"type"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type PostImage struct {
	ID       uuid.UUID `json:"id"`
	PostID   uuid.UUID `json:"post_id"`
	R2Key    string    `json:"r2_key"`
	Position int16     `json:"position"`
}

type PostLike struct {
	PostID    uuid.UUID          `json:"post_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	MemberID      string             `json:"member_id"`
	DisplayName   pgtype.Text        `json:"display_name"`
	Phone         pgtype.Text        `json:"phone"`
	RoleID        int16              `json:"role_id"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Status        string             `json:"status"`
	ApprovedBy    pgtype.UUID        `json:"approved_by"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	FamilyID   uuid.UUID          `json:"family_id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type Role struct {
	ID        int16              `json:"id"`
	Key       string             `json:"key"`
	Name      string             `json:"name"`
	Category  string             `json:"category"`
	Rank      int32              `json:"rank"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Sequence struct {
	Key          string             `json:"key"`
	CurrentValue int64              `json:"current_value"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
