// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
insert into notifications (recipient_id, actor_id, type, post_id, comment_id)
values ($1, $2, $3, $4, $5)
returning id, recipient_id, actor_id, type, post_id, comment_id, read_at, created_at
`

type CreateNotificationParams struct {
	RecipientID uuid.UUID   `json:"recipient_id"`
	ActorID     uuid.UUID   `json:"actor_id"`
	Type        string      `json:"type"`
	PostID      uuid.UUID   `json:"post_id"`
	CommentID   pgtype.UUID `json:"comment_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.RecipientID,
		arg.ActorID,
		arg.Type,
		arg.PostID,
		arg.CommentID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.ActorID,
		&i.Type,
		&i.PostID,
		&i.CommentID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
select id, recipient_id, actor_id, type, post_id, comment_id, read_at, created_at from notifications
where recipient_id = $1
  and ($2::timestamptz is null or created_at < $2)
order by created_at desc
limit $3
`

type ListNotificationsParams struct {
	RecipientID     uuid.UUID          `json:"recipient_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	RowLimit        int32              `json:"row_limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.RecipientID, arg.CursorCreatedAt, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.ActorID,
			&i.Type,
			&i.PostID,
			&i.CommentID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
update notifications set read_at = now() where recipient_id = $1 and read_at is null
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
update notifications set read_at = now() where id = $1 and recipient_id = $2 and read_at is null
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	return err
}
