// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentLog = `-- name: CreatePaymentLog :exec
insert into payment_logs (
  module, event, status, gateway, gateway_ref, amount_cents,
  user_id, related_id, message, raw_payload
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreatePaymentLogParams struct {
	Module      string      `json:"module"`
	Event       string      `json:"event"`
	Status      string      `json:"status"`
	Gateway     string      `json:"gateway"`
	GatewayRef  pgtype.Text `json:"gateway_ref"`
	AmountCents pgtype.Int4 `json:"amount_cents"`
	UserID      pgtype.UUID `json:"user_id"`
	RelatedID   pgtype.UUID `json:"related_id"`
	Message     pgtype.Text `json:"message"`
	RawPayload  pgtype.Text `json:"raw_payload"`
}

func (q *Queries) CreatePaymentLog(ctx context.Context, arg CreatePaymentLogParams) error {
	_, err := q.db.Exec(ctx, createPaymentLog,
		arg.Module,
		arg.Event,
		arg.Status,
		arg.Gateway,
		arg.GatewayRef,
		arg.AmountCents,
		arg.UserID,
		arg.RelatedID,
		arg.Message,
		arg.RawPayload,
	)
	return err
}

const deletePaymentLogsOlderThan = `-- name: DeletePaymentLogsOlderThan :execrows
delete from payment_logs where created_at < $1
`

// Retention 3 bulan (keputusan produk 2026-08-15) — dipanggil
// internal/retention, padanan pola sapuan audit_logs sedia ada.
func (q *Queries) DeletePaymentLogsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deletePaymentLogsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPaymentLogsByGatewayRef = `-- name: ListPaymentLogsByGatewayRef :many
select id, module, event, status, gateway, gateway_ref, amount_cents, user_id, related_id, message, raw_payload, created_at from payment_logs
where gateway = $1 and gateway_ref = $2
order by created_at asc
`

type ListPaymentLogsByGatewayRefParams struct {
	Gateway    string      `json:"gateway"`
	GatewayRef pgtype.Text `json:"gateway_ref"`
}

// Sejarah penuh satu bayaran (semua peristiwa: checkout, webhook,
// reconcile) — untuk diagnosis satu insiden, bukan tinjauan am.
func (q *Queries) ListPaymentLogsByGatewayRef(ctx context.Context, arg ListPaymentLogsByGatewayRefParams) ([]PaymentLog, error) {
	rows, err := q.db.Query(ctx, listPaymentLogsByGatewayRef, arg.Gateway, arg.GatewayRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentLog
	for rows.Next() {
		var i PaymentLog
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Event,
			&i.Status,
			&i.Gateway,
			&i.GatewayRef,
			&i.AmountCents,
			&i.UserID,
			&i.RelatedID,
			&i.Message,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPaymentLogs = `-- name: ListRecentPaymentLogs :many
select id, module, event, status, gateway, gateway_ref, amount_cents, user_id, related_id, message, raw_payload, created_at from payment_logs
where ($2::text is null or module = $2)
order by id desc
limit $1
`

type ListRecentPaymentLogsParams struct {
	Limit  int32       `json:"limit"`
	Module pgtype.Text `json:"module"`
}

// Tinjauan am terkini merentas modul — endpoint admin.
func (q *Queries) ListRecentPaymentLogs(ctx context.Context, arg ListRecentPaymentLogsParams) ([]PaymentLog, error) {
	rows, err := q.db.Query(ctx, listRecentPaymentLogs, arg.Limit, arg.Module)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentLog
	for rows.Next() {
		var i PaymentLog
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Event,
			&i.Status,
			&i.Gateway,
			&i.GatewayRef,
			&i.AmountCents,
			&i.UserID,
			&i.RelatedID,
			&i.Message,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
