// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
insert into posts (author_id, type, content)
values ($1, $2, $3)
returning id, author_id, type, content, created_at, edited_at, deleted_at
`

type CreatePostParams struct {
	AuthorID uuid.UUID `json:"author_id"`
	Type     string    `json:"type"`
	Content  string    `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Type, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPostImage = `-- name: CreatePostImage :one
insert into post_images (post_id, r2_key, "position")
values ($1, $2, $3)
returning id, post_id, r2_key, position
`

type CreatePostImageParams struct {
	PostID   uuid.UUID `json:"post_id"`
	R2Key    string    `json:"r2_key"`
	Position int16     `json:"position"`
}

func (q *Queries) CreatePostImage(ctx context.Context, arg CreatePostImageParams) (PostImage, error) {
	row := q.db.QueryRow(ctx, createPostImage, arg.PostID, arg.R2Key, arg.Position)
	var i PostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.R2Key,
		&i.Position,
	)
	return i, err
}

const getPostAuthorID = `-- name: GetPostAuthorID :one
select author_id from posts where id = $1 and deleted_at is null
`

func (q *Queries) GetPostAuthorID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPostAuthorID, id)
	var author_id uuid.UUID
	err := row.Scan(&author_id)
	return author_id, err
}

const getPostByID = `-- name: GetPostByID :one
select
  p.id, p.author_id, p.type, p.content, p.created_at, p.edited_at, p.deleted_at,
  u.email as author_email,
  pr.member_id as author_member_id,
  pr.display_name as author_display_name
from posts p
join users u on u.id = p.author_id
join profiles pr on pr.user_id = p.author_id
where p.id = $1 and p.deleted_at is null
`

type GetPostByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	Type              string             `json:"type"`
	Content           string             `json:"content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	AuthorEmail       string             `json:"author_email"`
	AuthorMemberID    string             `json:"author_member_id"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
}

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.AuthorEmail,
		&i.AuthorMemberID,
		&i.AuthorDisplayName,
	)
	return i, err
}

const listPostImagesByPostIDs = `-- name: ListPostImagesByPostIDs :many
select id, post_id, r2_key, position from post_images where post_id = any($1::uuid[]) order by post_id, "position"
`

func (q *Queries) ListPostImagesByPostIDs(ctx context.Context, postIds []uuid.UUID) ([]PostImage, error) {
	rows, err := q.db.Query(ctx, listPostImagesByPostIDs, postIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostImage
	for rows.Next() {
		var i PostImage
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.R2Key,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
select
  p.id, p.author_id, p.type, p.content, p.created_at, p.edited_at, p.deleted_at,
  u.email as author_email,
  pr.member_id as author_member_id,
  pr.display_name as author_display_name
from posts p
join users u on u.id = p.author_id
join profiles pr on pr.user_id = p.author_id
where p.deleted_at is null
  and ($1::timestamptz is null or p.created_at < $1)
order by p.created_at desc
limit $2
`

type ListPostsParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	RowLimit        int32              `json:"row_limit"`
}

type ListPostsRow struct {
	ID                uuid.UUID          `json:"id"`
	AuthorID          uuid.UUID          `json:"author_id"`
	Type              string             `json:"type"`
	Content           string             `json:"content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	AuthorEmail       string             `json:"author_email"`
	AuthorMemberID    string             `json:"author_member_id"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
}

// Cursor-based: pulang post yang created_at lebih lama daripada cursor
// (null cursor = page pertama).
func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.CursorCreatedAt, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.AuthorEmail,
			&i.AuthorMemberID,
			&i.AuthorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePost = `-- name: SoftDeletePost :exec
update posts set deleted_at = now() where id = $1
`

func (q *Queries) SoftDeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePost, id)
	return err
}

const updatePost = `-- name: UpdatePost :one
update posts
set content = $2, edited_at = now()
where id = $1 and deleted_at is null
returning id, author_id, type, content, created_at, edited_at, deleted_at
`

type UpdatePostParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost, arg.ID, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}
