// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
insert into profiles (user_id, member_id, role_id)
values ($1, $2, $3)
returning id, user_id, member_id, display_name, phone, role_id, email_verified, created_at
`

type CreateProfileParams struct {
	UserID   uuid.UUID `json:"user_id"`
	MemberID string    `json:"member_id"`
	RoleID   int16     `json:"role_id"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.MemberID, arg.RoleID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MemberID,
		&i.DisplayName,
		&i.Phone,
		&i.RoleID,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerifiedByUserID = `-- name: GetEmailVerifiedByUserID :one
select email_verified from profiles where user_id = $1
`

func (q *Queries) GetEmailVerifiedByUserID(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getEmailVerifiedByUserID, userID)
	var email_verified bool
	err := row.Scan(&email_verified)
	return email_verified, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
select
  p.id, p.user_id, p.member_id, p.display_name, p.phone, p.role_id, p.email_verified, p.created_at,
  u.email as email,
  r.key as role_key,
  r.name as role_name,
  r.category as role_category
from profiles p
join users u on u.id = p.user_id
join roles r on r.id = p.role_id
where p.user_id = $1
`

type GetProfileByUserIDRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	MemberID      string             `json:"member_id"`
	DisplayName   pgtype.Text        `json:"display_name"`
	Phone         pgtype.Text        `json:"phone"`
	RoleID        int16              `json:"role_id"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Email         string             `json:"email"`
	RoleKey       string             `json:"role_key"`
	RoleName      string             `json:"role_name"`
	RoleCategory  string             `json:"role_category"`
}

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MemberID,
		&i.DisplayName,
		&i.Phone,
		&i.RoleID,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.Email,
		&i.RoleKey,
		&i.RoleName,
		&i.RoleCategory,
	)
	return i, err
}

const getRoleCategoryByUserID = `-- name: GetRoleCategoryByUserID :one
select r.category
from profiles p
join roles r on r.id = p.role_id
where p.user_id = $1
`

func (q *Queries) GetRoleCategoryByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getRoleCategoryByUserID, userID)
	var category string
	err := row.Scan(&category)
	return category, err
}

const listProfiles = `-- name: ListProfiles :many
select
  p.id, p.user_id, p.member_id, p.display_name, p.phone, p.role_id, p.email_verified, p.created_at,
  r.key as role_key,
  r.name as role_name,
  r.category as role_category
from profiles p
join roles r on r.id = p.role_id
order by p.member_id
`

type ListProfilesRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	MemberID      string             `json:"member_id"`
	DisplayName   pgtype.Text        `json:"display_name"`
	Phone         pgtype.Text        `json:"phone"`
	RoleID        int16              `json:"role_id"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RoleKey       string             `json:"role_key"`
	RoleName      string             `json:"role_name"`
	RoleCategory  string             `json:"role_category"`
}

func (q *Queries) ListProfiles(ctx context.Context) ([]ListProfilesRow, error) {
	rows, err := q.db.Query(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfilesRow
	for rows.Next() {
		var i ListProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MemberID,
			&i.DisplayName,
			&i.Phone,
			&i.RoleID,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.RoleKey,
			&i.RoleName,
			&i.RoleCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
update profiles set email_verified = true where user_id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, userID)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
update profiles
set display_name = $2, phone = $3
where user_id = $1
returning id, user_id, member_id, display_name, phone, role_id, email_verified, created_at
`

type UpdateProfileParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Phone       pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.UserID, arg.DisplayName, arg.Phone)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MemberID,
		&i.DisplayName,
		&i.Phone,
		&i.RoleID,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}
