// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Atomic: DELETE...RETURNING dalam SATU statement, supaya refresh token
	// betul-betul single-use. Kalau dua request serentak hantar hash yang
	// sama (race), Postgres punya row-level lock jamin cuma SATU dapat row
	// balik (menang); yang satu lagi dapat 0 rows -> pgx.ErrNoRows -> 401.
	// Guna GetRefreshTokenByHash + DeleteRefreshToken berasingan sebelum ni
	// ada TOCTOU gap yang boleh buat DUA-DUA request refresh berjaya
	// serentak guna token yang sama.
	ConsumeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error
	DeleteDeviceTokenByOnesignalID(ctx context.Context, arg DeleteDeviceTokenByOnesignalIDParams) error
	DeleteEmailVerificationToken(ctx context.Context, id uuid.UUID) error
	DeleteEmailVerificationTokensByUser(ctx context.Context, userID uuid.UUID) error
	DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetProfileByUserID(ctx context.Context, userID uuid.UUID) (GetProfileByUserIDRow, error)
	GetRoleByID(ctx context.Context, id int16) (Role, error)
	GetRoleByKey(ctx context.Context, key string) (Role, error)
	GetRoleCategoryByUserID(ctx context.Context, userID uuid.UUID) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error)
	ListProfiles(ctx context.Context) ([]ListProfilesRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	MarkEmailVerified(ctx context.Context, userID uuid.UUID) error
	NextSequence(ctx context.Context, key string) (int64, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error
}

var _ Querier = (*Queries)(nil)
