// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveProfile(ctx context.Context, arg ApproveProfileParams) (Profile, error)
	CommentsLikedByUser(ctx context.Context, arg CommentsLikedByUserParams) ([]uuid.UUID, error)
	// Atomic single-use: UPDATE...RETURNING dalam SATU statement, guard
	// "consumed_at is null" jamin cuma SATU concurrent request menang kalau
	// hash sama dihantar serentak (row-level lock Postgres). Row TAK
	// dipadam (beza dari sebelum ni) — kekal untuk reuse detection: kalau
	// hash yang SAMA cuba consume LAGI selepas ni, row dah wujud tapi
	// consumed_at dah bukan null, so 0 rows returned di sini -> caller
	// boleh GetRefreshTokenByHash untuk detect reuse & revoke family.
	ConsumeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	CountCommentLikesByCommentIDs(ctx context.Context, commentIds []uuid.UUID) ([]CountCommentLikesByCommentIDsRow, error)
	CountCommentsByPostIDs(ctx context.Context, postIds []uuid.UUID) ([]CountCommentsByPostIDsRow, error)
	CountPostLikes(ctx context.Context, postID uuid.UUID) (int64, error)
	CountPostLikesByPostIDs(ctx context.Context, postIds []uuid.UUID) ([]CountPostLikesByPostIDsRow, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePendingUpload(ctx context.Context, arg CreatePendingUploadParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostImage(ctx context.Context, arg CreatePostImageParams) (PostImage, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Pruning polisi simpanan. Belum dipanggil dari mana-mana — sengaja,
	// supaya polisi diputuskan dulu sebelum data dibuang.
	DeleteAuditLogsBefore(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error
	DeleteDeviceTokenByOnesignalID(ctx context.Context, arg DeleteDeviceTokenByOnesignalIDParams) error
	DeleteEmailVerificationToken(ctx context.Context, id uuid.UUID) error
	DeleteEmailVerificationTokensByUser(ctx context.Context, userID uuid.UUID) error
	DeletePendingUpload(ctx context.Context, arg DeletePendingUploadParams) error
	// Tanpa skop user — untuk penyapu latar, bukan permintaan pengguna.
	DeletePendingUploadByKey(ctx context.Context, r2Key string) error
	DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error
	DeleteRefreshTokensByUser(ctx context.Context, userID uuid.UUID) error
	// on conflict do nothing: padam post yang sama dua kali (atau retry) tak
	// patut gagal, dan objek tu memang dah dalam gilir.
	EnqueueDeletedUpload(ctx context.Context, arg EnqueueDeletedUploadParams) error
	GetCommentAuthorID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
	GetDonationByGatewayRef(ctx context.Context, arg GetDonationByGatewayRefParams) (Donation, error)
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetEmailVerifiedByUserID(ctx context.Context, userID uuid.UUID) (bool, error)
	GetPostAuthorID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error)
	GetProfileByUserID(ctx context.Context, userID uuid.UUID) (GetProfileByUserIDRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, id int16) (Role, error)
	GetRoleByKey(ctx context.Context, key string) (Role, error)
	GetRoleCategoryByUserID(ctx context.Context, userID uuid.UUID) (string, error)
	GetStatusByUserID(ctx context.Context, userID uuid.UUID) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IsPendingUploadOwnedByUser(ctx context.Context, arg IsPendingUploadOwnedByUserParams) (bool, error)
	LikeComment(ctx context.Context, arg LikeCommentParams) error
	LikePost(ctx context.Context, arg LikePostParams) error
	// Feed audit global dengan tapisan pilihan. Pagination keyset guna
	// `before_id` (bukan OFFSET) — stabil walaupun baris baharu masuk
	// semasa pengguna membelek.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// Timeline satu entiti (cth semua suntingan pada satu post).
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	// Flat list, semua comment (top-level + reply) untuk satu post. Client
	// bina tree guna parent_comment_id.
	ListCommentsByPostID(ctx context.Context, postID uuid.UUID) ([]ListCommentsByPostIDRow, error)
	ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error)
	ListDueDeletedUploads(ctx context.Context, limit int32) ([]DeletedUpload, error)
	ListManagementUserIDs(ctx context.Context, category string) ([]uuid.UUID, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// Gambar milik post yang DAH dipadam tapi belum pernah digilir untuk
	// dibuang. Menangkap dua perkara: post yang dipadam SEBELUM gilir
	// pembersihan wujud, dan mana-mana kunci yang terlepas sejak itu.
	ListOrphanedPostImageKeys(ctx context.Context, limit int32) ([]string, error)
	ListPostImageKeys(ctx context.Context, postID uuid.UUID) ([]string, error)
	ListPostImagesByPostIDs(ctx context.Context, postIds []uuid.UUID) ([]PostImage, error)
	// Keyset pagination atas (created_at, id) — bukan created_at je, elak
	// row terlepas kalau ada tie timestamp betul-betul kat sempadan page
	// (null cursor = page pertama).
	ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	// Pending upload yang tak pernah dilekatkan pada mana-mana post.
	ListStalePendingUploads(ctx context.Context, arg ListStalePendingUploadsParams) ([]PendingUpload, error)
	// Senarai ahli yang boleh dilihat oleh SEORANG viewer tertentu. Tapisan
	// dibuat di peringkat SQL (bukan dalam Go) supaya baris yang viewer tak
	// layak tengok tak pernah pun keluar dari DB:
	//   max_rank             — siling hierarki keterlihatan; lihat
	//                          `visibleRankCeiling` di handlers/profile.go
	//   status               — penapis pilihan (cth 'pending' utk barisan
	//                          kelulusan management)
	//   include_all_statuses — management sahaja. Ahli biasa cuma nampak ahli
	//                          berstatus 'approved' (+ baris dia sendiri,
	//                          apa pun statusnya)
	ListVisibleProfiles(ctx context.Context, arg ListVisibleProfilesParams) ([]ListVisibleProfilesRow, error)
	MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error
	// Tandakan, jangan padam baris — lihat komen 'deleted_at' dlm migration.
	MarkDeletedUploadDone(ctx context.Context, r2Key string) error
	// Backoff eksponen ringkas, dihadkan pada 1 jam.
	MarkDeletedUploadFailed(ctx context.Context, arg MarkDeletedUploadFailedParams) error
	MarkEmailVerified(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	NextSequence(ctx context.Context, key string) (int64, error)
	PostLikedByUser(ctx context.Context, arg PostLikedByUserParams) (bool, error)
	// Untuk tandakan "liked_by_me" bila list post — pulang subset post_ids
	// yang user ni dah like.
	PostsLikedByUser(ctx context.Context, arg PostsLikedByUserParams) ([]uuid.UUID, error)
	RejectProfile(ctx context.Context, arg RejectProfileParams) (Profile, error)
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	SoftDeleteComment(ctx context.Context, id uuid.UUID) error
	SoftDeletePost(ctx context.Context, id uuid.UUID) error
	UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error
	UnlikePost(ctx context.Context, arg UnlikePostParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	// `status <> 'succeeded'` = 'succeeded' ialah keadaan TERMINAL: webhook
	// retry/replay (atau event lewat sampai tak ikut turutan) tak boleh
	// turunkan donation yang dah berjaya jadi 'failed'. Kad yang ditolak
	// kemudian dicuba semula atas PaymentIntent yang sama tetap boleh naik
	// 'failed' -> 'succeeded' (sebab itu bukan `status = 'pending'`).
	UpdateDonationStatusByGatewayRef(ctx context.Context, arg UpdateDonationStatusByGatewayRefParams) (Donation, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateProfileRole(ctx context.Context, arg UpdateProfileRoleParams) (Profile, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
