// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
update refresh_tokens
set consumed_at = now(), consumed_ip = $2
where token_hash = $1 and consumed_at is null
returning id, user_id, token_hash, expires_at, created_at, family_id, consumed_at, consumed_ip, user_agent, created_ip
`

type ConsumeRefreshTokenParams struct {
	TokenHash  string      `json:"token_hash"`
	ConsumedIp pgtype.Text `json:"consumed_ip"`
}

// Atomic single-use: UPDATE...RETURNING dalam SATU statement, guard
// "consumed_at is null" jamin cuma SATU concurrent request menang kalau
// hash sama dihantar serentak (row-level lock Postgres). Row TAK
// dipadam (beza dari sebelum ni) - kekal untuk reuse detection: kalau
// hash yang SAMA cuba consume LAGI selepas ni, row dah wujud tapi
// consumed_at dah bukan null, so 0 rows returned di sini -> caller
// boleh GetRefreshTokenByHash untuk detect reuse & revoke family.
//
// consumed_ip direkod supaya reuse-grace-window (auth.go) boleh semak IP
// request yang menang consume sama dengan IP request reuse - elak
// attacker yang curi token dari IP lain lolos grace window sekadar
// dengan race timing terhadap request pemilik sah.
func (q *Queries) ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, arg.TokenHash, arg.ConsumedIp)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ConsumedAt,
		&i.ConsumedIp,
		&i.UserAgent,
		&i.CreatedIp,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
insert into refresh_tokens (user_id, token_hash, expires_at, family_id, user_agent, created_ip)
values ($1, $2, $3, $4, $5, $6)
returning id, user_id, token_hash, expires_at, created_at, family_id, consumed_at, consumed_ip, user_agent, created_ip
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	FamilyID  uuid.UUID          `json:"family_id"`
	UserAgent pgtype.Text        `json:"user_agent"`
	CreatedIp pgtype.Text        `json:"created_ip"`
}

// user_agent/created_ip dirakam pada masa token dikeluarkan (issueTokens)
// semata-mata untuk skrin "sesi aktif" - supaya ahli boleh kenal device
// mana yang log masuk sebelum tekan "log keluar" padanya. Nilai mentah
// disimpan; tiada parsing jadi "iPhone/Chrome" di sini.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.FamilyID,
		arg.UserAgent,
		arg.CreatedIp,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ConsumedAt,
		&i.ConsumedIp,
		&i.UserAgent,
		&i.CreatedIp,
	)
	return i, err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
delete from refresh_tokens where token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const deleteRefreshTokenByIDAndUser = `-- name: DeleteRefreshTokenByIDAndUser :execrows
delete from refresh_tokens where id = $1 and user_id = $2
`

type DeleteRefreshTokenByIDAndUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Ownership dikuatkuasakan DALAM query (bukan semak dalam Go selepas
// fetch) - padanan GetAddressByIDAndUser. `:execrows` supaya caller
// boleh bezakan "dipadam" drpd "tiada baris" dan pulang 404 tanpa
// membocorkan kewujudan id sesi milik orang lain.
func (q *Queries) DeleteRefreshTokenByIDAndUser(ctx context.Context, arg DeleteRefreshTokenByIDAndUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshTokenByIDAndUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshTokensByIDsAndUser = `-- name: DeleteRefreshTokensByIDsAndUser :execrows
delete from refresh_tokens where user_id = $1 and id = any($2::uuid[])
`

type DeleteRefreshTokensByIDsAndUserParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Ids    []uuid.UUID `json:"ids"`
}

// Bulk revoke sesi aktif (skrin "log keluar device terpilih").
// Ownership dalam query: id milik ahli lain diabaikan senyap (0 baris
// dipadam), bukan 404 - elak kebocoran kewujudan id sesi orang lain.
func (q *Queries) DeleteRefreshTokensByIDsAndUser(ctx context.Context, arg DeleteRefreshTokensByIDsAndUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshTokensByIDsAndUser, arg.UserID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefreshTokensByUser = `-- name: DeleteRefreshTokensByUser :exec
delete from refresh_tokens where user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUser, userID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
select id, user_id, token_hash, expires_at, created_at, family_id, consumed_at, consumed_ip, user_agent, created_ip from refresh_tokens where token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ConsumedAt,
		&i.ConsumedIp,
		&i.UserAgent,
		&i.CreatedIp,
	)
	return i, err
}

const listActiveRefreshTokensByUser = `-- name: ListActiveRefreshTokensByUser :many
select id, user_id, token_hash, expires_at, created_at, family_id, consumed_at, consumed_ip, user_agent, created_ip from refresh_tokens
where user_id = $1 and expires_at > now()
order by created_at desc
`

// Sesi aktif milik pemanggil sendiri. `expires_at > now()` sahaja yang
// ditapis: baris yang dah dirotate (consumed_at bukan null) tapi family
// masih hidup sengaja TAK ditapis - ia masih mewakili device yang log
// masuk, dan menapisnya akan buat device aktif hilang dari senarai
// sebaik sahaja app refresh token.
func (q *Queries) ListActiveRefreshTokensByUser(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveRefreshTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.FamilyID,
			&i.ConsumedAt,
			&i.ConsumedIp,
			&i.UserAgent,
			&i.CreatedIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
delete from refresh_tokens where family_id = $1
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
