// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
update refresh_tokens
set consumed_at = now()
where token_hash = $1 and consumed_at is null
returning id, user_id, token_hash, expires_at, created_at, family_id, consumed_at
`

// Atomic single-use: UPDATE...RETURNING dalam SATU statement, guard
// "consumed_at is null" jamin cuma SATU concurrent request menang kalau
// hash sama dihantar serentak (row-level lock Postgres). Row TAK
// dipadam (beza dari sebelum ni) — kekal untuk reuse detection: kalau
// hash yang SAMA cuba consume LAGI selepas ni, row dah wujud tapi
// consumed_at dah bukan null, so 0 rows returned di sini -> caller
// boleh GetRefreshTokenByHash untuk detect reuse & revoke family.
func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ConsumedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
insert into refresh_tokens (user_id, token_hash, expires_at, family_id)
values ($1, $2, $3, $4)
returning id, user_id, token_hash, expires_at, created_at, family_id, consumed_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	FamilyID  uuid.UUID          `json:"family_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.FamilyID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ConsumedAt,
	)
	return i, err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
delete from refresh_tokens where token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const deleteRefreshTokensByUser = `-- name: DeleteRefreshTokensByUser :exec
delete from refresh_tokens where user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUser, userID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
select id, user_id, token_hash, expires_at, created_at, family_id, consumed_at from refresh_tokens where token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ConsumedAt,
	)
	return i, err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
delete from refresh_tokens where family_id = $1
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
