// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationPayment = `-- name: CreateRegistrationPayment :one
insert into registration_payments (user_id, amount_cents, currency, gateway, status)
values ($1, $2, $3, $4, 'pending')
returning id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type CreateRegistrationPaymentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	AmountCents int32     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	Gateway     string    `json:"gateway"`
}

// SENGAJA tanpa `gateway_ref` (L29, 2026-08-22). Baris ditulis SEBELUM
// bil gateway dicipta, jadi ref belum wujud pada titik ni — ia diisi
// oleh `SetRegistrationPaymentGatewayRef` sebaik createBill pulang.
//
// Susunan ni yang menjadikan bil yatim mustahil: kalau proses mati
// antara INSERT dan createBill, yang tinggal ialah baris 'pending' tanpa
// ref — kelihatan, boleh diaudit, dan TIADA bil untuk dibayar. Susunan
// lama (createBill dahulu) meninggalkan yang sebaliknya: bil yang boleh
// dibayar tanpa baris, yang webhook mahupun reconcile tak dapat lihat.
func (q *Queries) CreateRegistrationPayment(ctx context.Context, arg CreateRegistrationPaymentParams) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, createRegistrationPayment,
		arg.UserID,
		arg.AmountCents,
		arg.Currency,
		arg.Gateway,
	)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const expireRegistrationPayment = `-- name: ExpireRegistrationPayment :one
update registration_payments
set status = 'failed'
where id = $1 and status = 'pending'
returning id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at
`

// Tandakan percubaan bayaran 'pending' sebagai 'failed' (bil tamat tempoh
// atau dibatalkan admin). Guard `status = 'pending'` — 'succeeded'
// terminal; reconcile/webhook lewat boleh naik 'failed'->'succeeded'.
func (q *Queries) ExpireRegistrationPayment(ctx context.Context, id uuid.UUID) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, expireRegistrationPayment, id)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPendingRegistrationPayment = `-- name: GetLatestPendingRegistrationPayment :one
select id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at from registration_payments
where user_id = $1 and status = 'pending'
order by created_at desc
limit 1
`

// Bil yuran pendaftaran 'pending' TERKINI untuk seorang ahli — admin
// batalkan bil sebelum langkau bayaran, atau sapuan lapuk.
func (q *Queries) GetLatestPendingRegistrationPayment(ctx context.Context, userID uuid.UUID) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, getLatestPendingRegistrationPayment, userID)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRegistrationPaymentStatus = `-- name: GetLatestRegistrationPaymentStatus :one
select status from registration_payments
where user_id = $1
order by (status = 'succeeded') desc, created_at desc
limit 1
`

// Untuk `/me` — Flutter perlukan ni supaya ahli nampak bayaran mereka
// berjaya/gagal/menunggu, bukan senyap (gap ditemui 2026-08-15: bayaran
// gagal/berjaya dua-dua direkod betul dalam DB tapi client tak pernah
// baca, jadi ahli nampak "tiada apa berlaku" tak kira hasil sebenar).
// `pgx.ErrNoRows` bermakna ahli tak pernah cuba bayar langsung — caller
// (Go) layan tu sebagai null, bukan ralat.
//
// Utamakan 'succeeded' dulu (Opus verify 2026-08-15): `Checkout` cuma
// sekat bayaran BERULANG bila dah ada baris 'succeeded' — kalau ahli
// tekan Bayar dua kali (baris A, lepas tu B) dan bayar bil A dulu,
// 'order by created_at desc' semata-mata akan pulang B ('pending', baris
// LEBIH BAHARU) walhal A dah 'succeeded' — ahli nampak "sedang disahkan"
// selama-lamanya walau dah bayar. `(status = 'succeeded') desc` letak
// baris succeeded MANA-MANA PUN di atas dulu; `created_at desc` cuma
// pemisah antara baris tak-succeeded (paparkan percubaan TERKINI).
func (q *Queries) GetLatestRegistrationPaymentStatus(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLatestRegistrationPaymentStatus, userID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getMyRegistrationPaymentByID = `-- name: GetMyRegistrationPaymentByID :one
select rp.id, rp.amount_cents, rp.currency, rp.gateway, rp.gateway_ref, rp.status, rp.created_at,
  p.member_id, p.display_name, u.email
from registration_payments rp
join profiles p on p.user_id = rp.user_id
join users u on u.id = rp.user_id
where rp.id = $1 and rp.user_id = $2
`

type GetMyRegistrationPaymentByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetMyRegistrationPaymentByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	AmountCents int32              `json:"amount_cents"`
	Currency    string             `json:"currency"`
	Gateway     string             `json:"gateway"`
	GatewayRef  pgtype.Text        `json:"gateway_ref"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MemberID    string             `json:"member_id"`
	DisplayName pgtype.Text        `json:"display_name"`
	Email       string             `json:"email"`
}

// Resit — hanya baris SENDIRI (user_id caller), sertakan medan papar
// (no. ahli/nama/emel) supaya handler resit tak perlu query kedua.
func (q *Queries) GetMyRegistrationPaymentByID(ctx context.Context, arg GetMyRegistrationPaymentByIDParams) (GetMyRegistrationPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getMyRegistrationPaymentByID, arg.ID, arg.UserID)
	var i GetMyRegistrationPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
		&i.MemberID,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}

const hasPendingRegistrationPayment = `-- name: HasPendingRegistrationPayment :one
select exists(
  select 1 from registration_payments
  where user_id = $1 and status = 'pending'
)
`

// Baris 'pending' MANA-MANA PUN — SENGAJA TANPA tapisan `gateway_ref is
// not null` (Opus verify 2026-08-24: tak macam
// ListPendingRegistrationPaymentsOlderThan, baris `gateway_ref` NULL di
// sini BUKAN bukti "tiada bil sebenar". Lihat komen "TETINGKAP BAKI" di
// `registration_payment.go` `Checkout` — createBill BOLEH berjaya
// [bil sebenar wujud di ToyyibPay] tapi `SetRegistrationPaymentGatewayRef`
// gagal selepas tu, meninggalkan baris 'pending' TANPA ref walaupun bil
// boleh dibayar. Tapisan ref bertujuan bagi query reconcile [nak tahu
// bil MANA nak poll], bukan bagi gate ni [nak tahu ADA-TAK bil terbuka
// langsung] — dua soalan berbeza.
//
// Dipakai oleh gate langkau-bayaran (`ApproveMember` bypass, admin/
// superadmin) — kalau baris begini wujud, ahli boleh terima 2 pengesahan
// bayaran (tunai + bil online lama yang masih dibayar lepas approve),
// jadi bypass MESTI ditolak sehingga baris lama diselesaikan (webhook/
// pautan manual tandakan succeeded/failed) atau tamat tempoh
// (registrationsweep + billExpiryDate ToyyibPay).
func (q *Queries) HasPendingRegistrationPayment(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingRegistrationPayment, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasSucceededRegistrationPayment = `-- name: HasSucceededRegistrationPayment :one
select exists(
  select 1 from registration_payments where user_id = $1 and status = 'succeeded'
)
`

func (q *Queries) HasSucceededRegistrationPayment(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasSucceededRegistrationPayment, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMyRegistrationPayments = `-- name: ListMyRegistrationPayments :many
select id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at from registration_payments
where user_id = $1
order by created_at desc
`

// Sejarah PENUH percubaan yuran pendaftaran seorang ahli (bukan cuma
// status terkini macam GetLatestRegistrationPaymentStatus) — utk skrin
// "Sejarah Bayaran Saya".
func (q *Queries) ListMyRegistrationPayments(ctx context.Context, userID uuid.UUID) ([]RegistrationPayment, error) {
	rows, err := q.db.Query(ctx, listMyRegistrationPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationPayment
	for rows.Next() {
		var i RegistrationPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountCents,
			&i.Currency,
			&i.Gateway,
			&i.GatewayRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRegistrationPaymentsOlderThan = `-- name: ListPendingRegistrationPaymentsOlderThan :many
select id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at from registration_payments
where status = 'pending'
  and gateway_ref is not null
  and created_at < $1
  and created_at > $2
order by created_at
limit $3
`

type ListPendingRegistrationPaymentsOlderThanParams struct {
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	Oldest      pgtype.Timestamptz `json:"oldest"`
	RowLimit    int32              `json:"row_limit"`
}

// Baris 'pending' yang dah cukup umur untuk layak disemak semula terus
// pada gateway (internal/paymentreconcile) — bukan `status <> 'succeeded'`
// macam query UPDATE di atas, sengaja `status = 'pending'` sahaja: baris
// 'failed' TAK perlu disemak semula (terminal jugak, sama macam
// 'succeeded', reconcile tak sepatutnya "hidupkan semula" bayaran gagal
// tanpa ahli cuba lagi secara eksplisit — bayaran baharu akan hasilkan
// baris baharu).
//
// TINGKAP ATAS + LIMIT (L30, 2026-08-22). Sebelum ni query ni ada had
// umur BAWAH sahaja, dan baris yang ditinggalkan TAK PERNAH keluar
// daripada 'pending': bil ToyyibPay yang tak dibayar pulang
// `No data found!` selama-lamanya, jadi `CheckStatus` pulang "pending"
// selama-lamanya. Setiap checkout terbiar kekal dalam senarai semakan
// SELAMANYA, dan setiap 30 minit ia satu panggilan HTTP keluar lagi —
// bebanan yang membesar secara monotonik sepanjang hayat sistem.
//
// `stale_before` = had bawah (cukup umur untuk layak disemak).
// `oldest` = had atas: lebih tua drpd ni bukan lagi kerja rekonsiliasi,
// ia kerja pembersihan. Baris begitu TIDAK hilang — ia kekal dalam DB
// dan tetap kelihatan melalui /admin/payments; ia cuma berhenti dipoll.
// `gateway_ref is not null` (L29, 2026-08-22): baris tanpa ref bermakna
// createBill tak pernah berjaya, jadi tiada bil untuk ditanya pada
// gateway. Padanan skop `ListPendingActivityRegistrationsOlderThan`,
// yang sudah lama menapis dgn cara sama atas sebab yang sama.
func (q *Queries) ListPendingRegistrationPaymentsOlderThan(ctx context.Context, arg ListPendingRegistrationPaymentsOlderThanParams) ([]RegistrationPayment, error) {
	rows, err := q.db.Query(ctx, listPendingRegistrationPaymentsOlderThan, arg.StaleBefore, arg.Oldest, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationPayment
	for rows.Next() {
		var i RegistrationPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountCents,
			&i.Currency,
			&i.Gateway,
			&i.GatewayRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingRegistrationPayments = `-- name: ListStalePendingRegistrationPayments :many
select id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at from registration_payments
where status = 'pending'
  and created_at < $1
order by created_at
limit $2
`

type ListStalePendingRegistrationPaymentsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

// Baris 'pending' lebih tua drpd cutoff — internal/registrationsweep.
// TIADA tapisan gateway_ref: baris tanpa ref (createBill gagal sebelum
// ref) turut perlu ditandakan 'failed' supaya gate bypass/admin tak
// tersekat. Baris dengan ref disemak gateway DULU dalam Go sebelum
// ExpireRegistrationPayment.
func (q *Queries) ListStalePendingRegistrationPayments(ctx context.Context, arg ListStalePendingRegistrationPaymentsParams) ([]RegistrationPayment, error) {
	rows, err := q.db.Query(ctx, listStalePendingRegistrationPayments, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationPayment
	for rows.Next() {
		var i RegistrationPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountCents,
			&i.Currency,
			&i.Gateway,
			&i.GatewayRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRegistrationPaymentFailed = `-- name: MarkRegistrationPaymentFailed :exec
update registration_payments
set status = 'failed'
where id = $1 and gateway_ref is null
`

// Dipanggil bila createBill GAGAL selepas baris dicipta. Baris dikekalkan
// (bukan dipadam) supaya sejarah "Bayaran Saya" ahli menunjukkan
// percubaan itu benar-benar berlaku — dan `ListPendingRegistrationPayments
// OlderThan` tak perlu menapis baris yang takkan pernah ada bil.
//
// Guard `gateway_ref is null` memastikan ni tak boleh menjatuhkan bayaran
// yang bilnya SUDAH dicipta.
func (q *Queries) MarkRegistrationPaymentFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRegistrationPaymentFailed, id)
	return err
}

const setRegistrationPaymentGatewayRef = `-- name: SetRegistrationPaymentGatewayRef :one
update registration_payments
set gateway_ref = $2
where id = $1 and gateway_ref is null
returning id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type SetRegistrationPaymentGatewayRefParams struct {
	ID         uuid.UUID   `json:"id"`
	GatewayRef pgtype.Text `json:"gateway_ref"`
}

// Isi `gateway_ref` sebaik createBill berjaya. Dikunci pada `id` (bukan
// ref) sebab ref itulah yang belum wujud.
//
// Guard `gateway_ref is null` menjadikannya sekali-tulis: sebaik bil
// dikaitkan, tiada laluan boleh menunjuknya kepada bil LAIN. Tanpa
// guard, pepijat di tempat lain boleh menulis ganti ref bagi bayaran
// yang sudah berjaya dan mengalihkan rekod kewangan kepada bil orang
// lain.
func (q *Queries) SetRegistrationPaymentGatewayRef(ctx context.Context, arg SetRegistrationPaymentGatewayRefParams) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, setRegistrationPaymentGatewayRef, arg.ID, arg.GatewayRef)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateRegistrationPaymentStatusByGatewayRef = `-- name: UpdateRegistrationPaymentStatusByGatewayRef :one
update registration_payments
set status = $3
where gateway = $1 and gateway_ref = $2 and status <> 'succeeded'
returning id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type UpdateRegistrationPaymentStatusByGatewayRefParams struct {
	Gateway    string      `json:"gateway"`
	GatewayRef pgtype.Text `json:"gateway_ref"`
	Status     string      `json:"status"`
}

// `status <> 'succeeded'` = 'succeeded' ialah keadaan TERMINAL: webhook
// retry/replay (atau event lewat sampai tak ikut turutan) tak boleh
// turunkan bayaran yang dah berjaya jadi 'failed'. Percubaan gagal yang
// dicuba semula pada gateway_ref yang sama tetap boleh naik
// 'failed' -> 'succeeded' (sebab itu bukan `status = 'pending'`).
func (q *Queries) UpdateRegistrationPaymentStatusByGatewayRef(ctx context.Context, arg UpdateRegistrationPaymentStatusByGatewayRefParams) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, updateRegistrationPaymentStatusByGatewayRef, arg.Gateway, arg.GatewayRef, arg.Status)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
