// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationPayment = `-- name: CreateRegistrationPayment :one
insert into registration_payments (user_id, amount_cents, currency, gateway, gateway_ref, status)
values ($1, $2, $3, $4, $5, 'pending')
returning id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type CreateRegistrationPaymentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	AmountCents int32     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	Gateway     string    `json:"gateway"`
	GatewayRef  string    `json:"gateway_ref"`
}

func (q *Queries) CreateRegistrationPayment(ctx context.Context, arg CreateRegistrationPaymentParams) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, createRegistrationPayment,
		arg.UserID,
		arg.AmountCents,
		arg.Currency,
		arg.Gateway,
		arg.GatewayRef,
	)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRegistrationPaymentStatus = `-- name: GetLatestRegistrationPaymentStatus :one
select status from registration_payments
where user_id = $1
order by (status = 'succeeded') desc, created_at desc
limit 1
`

// Untuk `/me` — Flutter perlukan ni supaya ahli nampak bayaran mereka
// berjaya/gagal/menunggu, bukan senyap (gap ditemui 2026-08-15: bayaran
// gagal/berjaya dua-dua direkod betul dalam DB tapi client tak pernah
// baca, jadi ahli nampak "tiada apa berlaku" tak kira hasil sebenar).
// `pgx.ErrNoRows` bermakna ahli tak pernah cuba bayar langsung — caller
// (Go) layan tu sebagai null, bukan ralat.
//
// Utamakan 'succeeded' dulu (Opus verify 2026-08-15): `Checkout` cuma
// sekat bayaran BERULANG bila dah ada baris 'succeeded' — kalau ahli
// tekan Bayar dua kali (baris A, lepas tu B) dan bayar bil A dulu,
// 'order by created_at desc' semata-mata akan pulang B ('pending', baris
// LEBIH BAHARU) walhal A dah 'succeeded' — ahli nampak "sedang disahkan"
// selama-lamanya walau dah bayar. `(status = 'succeeded') desc` letak
// baris succeeded MANA-MANA PUN di atas dulu; `created_at desc` cuma
// pemisah antara baris tak-succeeded (paparkan percubaan TERKINI).
func (q *Queries) GetLatestRegistrationPaymentStatus(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLatestRegistrationPaymentStatus, userID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const hasSucceededRegistrationPayment = `-- name: HasSucceededRegistrationPayment :one
select exists(
  select 1 from registration_payments where user_id = $1 and status = 'succeeded'
)
`

func (q *Queries) HasSucceededRegistrationPayment(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasSucceededRegistrationPayment, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMyRegistrationPayments = `-- name: ListMyRegistrationPayments :many
select id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at from registration_payments
where user_id = $1
order by created_at desc
`

// Sejarah PENUH percubaan yuran pendaftaran seorang ahli (bukan cuma
// status terkini macam GetLatestRegistrationPaymentStatus) — utk skrin
// "Sejarah Bayaran Saya".
func (q *Queries) ListMyRegistrationPayments(ctx context.Context, userID uuid.UUID) ([]RegistrationPayment, error) {
	rows, err := q.db.Query(ctx, listMyRegistrationPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationPayment
	for rows.Next() {
		var i RegistrationPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountCents,
			&i.Currency,
			&i.Gateway,
			&i.GatewayRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRegistrationPaymentsOlderThan = `-- name: ListPendingRegistrationPaymentsOlderThan :many
select id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at from registration_payments
where status = 'pending' and created_at < $1
order by created_at
`

// Baris 'pending' yang dah cukup umur untuk layak disemak semula terus
// pada gateway (internal/paymentreconcile) — bukan `status <> 'succeeded'`
// macam query UPDATE di atas, sengaja `status = 'pending'` sahaja: baris
// 'failed' TAK perlu disemak semula (terminal jugak, sama macam
// 'succeeded', reconcile tak sepatutnya "hidupkan semula" bayaran gagal
// tanpa ahli cuba lagi secara eksplisit — bayaran baharu akan hasilkan
// baris baharu).
func (q *Queries) ListPendingRegistrationPaymentsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) ([]RegistrationPayment, error) {
	rows, err := q.db.Query(ctx, listPendingRegistrationPaymentsOlderThan, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistrationPayment
	for rows.Next() {
		var i RegistrationPayment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountCents,
			&i.Currency,
			&i.Gateway,
			&i.GatewayRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistrationPaymentStatusByGatewayRef = `-- name: UpdateRegistrationPaymentStatusByGatewayRef :one
update registration_payments
set status = $3
where gateway = $1 and gateway_ref = $2 and status <> 'succeeded'
returning id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type UpdateRegistrationPaymentStatusByGatewayRefParams struct {
	Gateway    string `json:"gateway"`
	GatewayRef string `json:"gateway_ref"`
	Status     string `json:"status"`
}

// `status <> 'succeeded'` = 'succeeded' ialah keadaan TERMINAL: webhook
// retry/replay (atau event lewat sampai tak ikut turutan) tak boleh
// turunkan bayaran yang dah berjaya jadi 'failed'. Percubaan gagal yang
// dicuba semula pada gateway_ref yang sama tetap boleh naik
// 'failed' -> 'succeeded' (sebab itu bukan `status = 'pending'`).
func (q *Queries) UpdateRegistrationPaymentStatusByGatewayRef(ctx context.Context, arg UpdateRegistrationPaymentStatusByGatewayRefParams) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, updateRegistrationPaymentStatusByGatewayRef, arg.Gateway, arg.GatewayRef, arg.Status)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
