// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration_payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRegistrationPayment = `-- name: CreateRegistrationPayment :one
insert into registration_payments (user_id, amount_cents, currency, gateway, gateway_ref, status)
values ($1, $2, $3, $4, $5, 'pending')
returning id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type CreateRegistrationPaymentParams struct {
	UserID      uuid.UUID `json:"user_id"`
	AmountCents int32     `json:"amount_cents"`
	Currency    string    `json:"currency"`
	Gateway     string    `json:"gateway"`
	GatewayRef  string    `json:"gateway_ref"`
}

func (q *Queries) CreateRegistrationPayment(ctx context.Context, arg CreateRegistrationPaymentParams) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, createRegistrationPayment,
		arg.UserID,
		arg.AmountCents,
		arg.Currency,
		arg.Gateway,
		arg.GatewayRef,
	)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const hasSucceededRegistrationPayment = `-- name: HasSucceededRegistrationPayment :one
select exists(
  select 1 from registration_payments where user_id = $1 and status = 'succeeded'
)
`

func (q *Queries) HasSucceededRegistrationPayment(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasSucceededRegistrationPayment, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRegistrationPaymentStatusByGatewayRef = `-- name: UpdateRegistrationPaymentStatusByGatewayRef :one
update registration_payments
set status = $3
where gateway = $1 and gateway_ref = $2 and status <> 'succeeded'
returning id, user_id, amount_cents, currency, gateway, gateway_ref, status, created_at
`

type UpdateRegistrationPaymentStatusByGatewayRefParams struct {
	Gateway    string `json:"gateway"`
	GatewayRef string `json:"gateway_ref"`
	Status     string `json:"status"`
}

// `status <> 'succeeded'` = 'succeeded' ialah keadaan TERMINAL: webhook
// retry/replay (atau event lewat sampai tak ikut turutan) tak boleh
// turunkan bayaran yang dah berjaya jadi 'failed'. Percubaan gagal yang
// dicuba semula pada gateway_ref yang sama tetap boleh naik
// 'failed' -> 'succeeded' (sebab itu bukan `status = 'pending'`).
func (q *Queries) UpdateRegistrationPaymentStatusByGatewayRef(ctx context.Context, arg UpdateRegistrationPaymentStatusByGatewayRefParams) (RegistrationPayment, error) {
	row := q.db.QueryRow(ctx, updateRegistrationPaymentStatusByGatewayRef, arg.Gateway, arg.GatewayRef, arg.Status)
	var i RegistrationPayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
