// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"
)

const getRoleByID = `-- name: GetRoleByID :one
select id, key, name, category, rank, created_at from roles where id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int16) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Category,
		&i.Rank,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByKey = `-- name: GetRoleByKey :one
select id, key, name, category, rank, created_at from roles where key = $1
`

func (q *Queries) GetRoleByKey(ctx context.Context, key string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByKey, key)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Category,
		&i.Rank,
		&i.CreatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
select id, key, name, category, rank, created_at from roles order by rank
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Category,
			&i.Rank,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
