// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sequences.sql

package sqlc

import (
	"context"
)

const nextSequence = `-- name: NextSequence :one
insert into sequences (key, current_value, updated_at)
values ($1, 1, now())
on conflict (key) do update set
  current_value = sequences.current_value + 1,
  updated_at = now()
returning current_value
`

func (q *Queries) NextSequence(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRow(ctx, nextSequence, key)
	var current_value int64
	err := row.Scan(&current_value)
	return current_value, err
}
