// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_link_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeTelegramLinkToken = `-- name: ConsumeTelegramLinkToken :one
delete from telegram_link_tokens
where token_hash = $1
returning id, user_id, token_hash, expires_at, created_at
`

// Tuntut token secara ATOMIK: satu pernyataan, `delete ... returning`.
// Padanan tepat ConsumePasswordResetToken (queries/password_reset_tokens.sql)
// dan atas sebab yang SAMA -- baca-dahulu-kemudian-tulis ada jurang
// TOCTOU yang membenarkan dua permintaan serentak kedua-duanya lulus.
func (q *Queries) ConsumeTelegramLinkToken(ctx context.Context, tokenHash string) (TelegramLinkToken, error) {
	row := q.db.QueryRow(ctx, consumeTelegramLinkToken, tokenHash)
	var i TelegramLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTelegramLinkToken = `-- name: CreateTelegramLinkToken :one
insert into telegram_link_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, user_id, token_hash, expires_at, created_at
`

type CreateTelegramLinkTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTelegramLinkToken(ctx context.Context, arg CreateTelegramLinkTokenParams) (TelegramLinkToken, error) {
	row := q.db.QueryRow(ctx, createTelegramLinkToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i TelegramLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTelegramLinkTokensByUser = `-- name: DeleteTelegramLinkTokensByUser :exec
delete from telegram_link_tokens where user_id = $1
`

func (q *Queries) DeleteTelegramLinkTokensByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTelegramLinkTokensByUser, userID)
	return err
}
