// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPendingUpload = `-- name: CreatePendingUpload :exec
insert into pending_uploads (r2_key, user_id) values ($1, $2)
`

type CreatePendingUploadParams struct {
	R2Key  string    `json:"r2_key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreatePendingUpload(ctx context.Context, arg CreatePendingUploadParams) error {
	_, err := q.db.Exec(ctx, createPendingUpload, arg.R2Key, arg.UserID)
	return err
}

const deletePendingUpload = `-- name: DeletePendingUpload :exec
delete from pending_uploads where r2_key = $1 and user_id = $2
`

type DeletePendingUploadParams struct {
	R2Key  string    `json:"r2_key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePendingUpload(ctx context.Context, arg DeletePendingUploadParams) error {
	_, err := q.db.Exec(ctx, deletePendingUpload, arg.R2Key, arg.UserID)
	return err
}

const isPendingUploadOwnedByUser = `-- name: IsPendingUploadOwnedByUser :one
select exists(select 1 from pending_uploads where r2_key = $1 and user_id = $2)
`

type IsPendingUploadOwnedByUserParams struct {
	R2Key  string    `json:"r2_key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsPendingUploadOwnedByUser(ctx context.Context, arg IsPendingUploadOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPendingUploadOwnedByUser, arg.R2Key, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
