// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingUpload = `-- name: CreatePendingUpload :exec
insert into pending_uploads (r2_key, user_id) values ($1, $2)
`

type CreatePendingUploadParams struct {
	R2Key  string    `json:"r2_key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreatePendingUpload(ctx context.Context, arg CreatePendingUploadParams) error {
	_, err := q.db.Exec(ctx, createPendingUpload, arg.R2Key, arg.UserID)
	return err
}

const deleteDoneDeletedUploadsBefore = `-- name: DeleteDoneDeletedUploadsBefore :execrows
delete from deleted_uploads
where deleted_at is not null and deleted_at < $1
`

// Prune batu nisan lama. Selamat sebab objek R2 sendiri dah tiada; baris
// ni cuma menghalang penggiliran semula, dan objek yang dah dipadam
// takkan muncul semula dalam post_images/pending_uploads.
func (q *Queries) DeleteDoneDeletedUploadsBefore(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDoneDeletedUploadsBefore, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingUpload = `-- name: DeletePendingUpload :exec
delete from pending_uploads where r2_key = $1 and user_id = $2
`

type DeletePendingUploadParams struct {
	R2Key  string    `json:"r2_key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePendingUpload(ctx context.Context, arg DeletePendingUploadParams) error {
	_, err := q.db.Exec(ctx, deletePendingUpload, arg.R2Key, arg.UserID)
	return err
}

const deletePendingUploadByKey = `-- name: DeletePendingUploadByKey :exec
delete from pending_uploads where r2_key = $1
`

// Tanpa skop user — untuk penyapu latar, bukan permintaan pengguna.
func (q *Queries) DeletePendingUploadByKey(ctx context.Context, r2Key string) error {
	_, err := q.db.Exec(ctx, deletePendingUploadByKey, r2Key)
	return err
}

const enqueueDeletedUpload = `-- name: EnqueueDeletedUpload :exec
insert into deleted_uploads (r2_key, reason)
values ($1, $2)
on conflict (r2_key) do nothing
`

type EnqueueDeletedUploadParams struct {
	R2Key  string `json:"r2_key"`
	Reason string `json:"reason"`
}

// on conflict do nothing: padam post yang sama dua kali (atau retry) tak
// patut gagal, dan objek tu memang dah dalam gilir.
func (q *Queries) EnqueueDeletedUpload(ctx context.Context, arg EnqueueDeletedUploadParams) error {
	_, err := q.db.Exec(ctx, enqueueDeletedUpload, arg.R2Key, arg.Reason)
	return err
}

const isPendingUploadOwnedByUser = `-- name: IsPendingUploadOwnedByUser :one
select exists(select 1 from pending_uploads where r2_key = $1 and user_id = $2)
`

type IsPendingUploadOwnedByUserParams struct {
	R2Key  string    `json:"r2_key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsPendingUploadOwnedByUser(ctx context.Context, arg IsPendingUploadOwnedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPendingUploadOwnedByUser, arg.R2Key, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDueDeletedUploads = `-- name: ListDueDeletedUploads :many
select r2_key, reason, attempts, last_error, deleted_at, next_attempt_at, created_at from deleted_uploads
where deleted_at is null and next_attempt_at <= now()
order by next_attempt_at
limit $1
`

func (q *Queries) ListDueDeletedUploads(ctx context.Context, limit int32) ([]DeletedUpload, error) {
	rows, err := q.db.Query(ctx, listDueDeletedUploads, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletedUpload
	for rows.Next() {
		var i DeletedUpload
		if err := rows.Scan(
			&i.R2Key,
			&i.Reason,
			&i.Attempts,
			&i.LastError,
			&i.DeletedAt,
			&i.NextAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingUploads = `-- name: ListStalePendingUploads :many
select pu.r2_key, pu.user_id, pu.created_at from pending_uploads pu
where pu.created_at < $1
  and not exists (
    select 1 from post_images pi where pi.r2_key = pu.r2_key
  )
  and not exists (
    select 1 from profiles pr where pr.avatar_r2_key = pu.r2_key
  )
order by pu.created_at
limit $2
`

type ListStalePendingUploadsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

// Pending upload yang tak pernah dilekatkan pada mana-mana post ATAU profil.
//
// Dua klausa `not exists` ni BUKAN pendua kepada laluan Go (Opus verify
// 2026-08-22, L28). Baris yang dipulangkan di sini ialah senarai PADAM:
// semuanya akan digilir ke `deleted_uploads` dan objek R2nya dibuang.
// Sebelum ni query cuma menapis ikut UMUR dan bergantung SEPENUHNYA pada
// baris dikeluarkan semasa post dicipta — sedangkan laluan itu
// (`posts.go`) mengabaikan ralat `DeletePendingUpload`, jadi satu DELETE
// yang gagal bermakna gambar post yang MASIH dipaparkan dipadam 6 jam
// kemudian, kekal, tanpa ralat di mana-mana.
//
// Laluan Go kini menyemak ralat itu juga, tapi kedua-dua lapisan
// dikekalkan dengan sengaja: kos melanggar invarian ni ialah kehilangan
// data yang tak boleh dipulihkan, dan semakan di SINI turut melindungi
// mana-mana laluan tulis MASA HADAPAN yang terlupa mengeluarkan barisnya.
//
// Laluan avatar (`applyAvatar`) sentiasa menyemak ralatnya, jadi klausa
// `profiles` lebih kepada simetri drpd pembaikan pepijat — tapi tanpa ia,
// query ni betul atas sebab yang bergantung pada fail LAIN, dan itulah
// tepatnya bentuk kelemahan yang L28 wujud untuk hapuskan.
func (q *Queries) ListStalePendingUploads(ctx context.Context, arg ListStalePendingUploadsParams) ([]PendingUpload, error) {
	rows, err := q.db.Query(ctx, listStalePendingUploads, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingUpload
	for rows.Next() {
		var i PendingUpload
		if err := rows.Scan(&i.R2Key, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeletedUploadDone = `-- name: MarkDeletedUploadDone :exec
update deleted_uploads set deleted_at = now() where r2_key = $1
`

// Tandakan, jangan padam baris — lihat komen 'deleted_at' dlm migration.
func (q *Queries) MarkDeletedUploadDone(ctx context.Context, r2Key string) error {
	_, err := q.db.Exec(ctx, markDeletedUploadDone, r2Key)
	return err
}

const markDeletedUploadFailed = `-- name: MarkDeletedUploadFailed :exec
update deleted_uploads
set attempts = attempts + 1,
    last_error = $2,
    next_attempt_at = now() + least(power(2, attempts)::int, 60) * interval '1 minute'
where r2_key = $1
`

type MarkDeletedUploadFailedParams struct {
	R2Key     string      `json:"r2_key"`
	LastError pgtype.Text `json:"last_error"`
}

// Backoff eksponen ringkas, dihadkan pada 1 jam.
func (q *Queries) MarkDeletedUploadFailed(ctx context.Context, arg MarkDeletedUploadFailedParams) error {
	_, err := q.db.Exec(ctx, markDeletedUploadFailed, arg.R2Key, arg.LastError)
	return err
}
